- publish-utils/build.gradle
The constants.properties is only one directory beneath publish-utils now - the gradle.build file still assumes it is two directories beneath like it was in the corda repo
> Fix relative directory issue causing local install issue

- api-scanner/README.md
Fix documentation links for API Scanner plugin now that these plugins are no longer part of the Corda repository.
> Fix broken links in API Scanner plugin's documentation.

- build.gradle
Using the `Wrapper` task enables IntelliJ to work out which version of the Gradle APIs it is supposed to be building against.
> Configure the Gradle wrapper via the Wrapper task.

- api-scanner/src/main/java/net/corda/plugins/ScanApi.java
The '.' matches _any_ character in a regular expression, but we require a literal dot for a file extension.
> Force '.' to be an ordinary character in regex.

- api-scanner/src/test/resources/kotlin-annotations/build.gradle
- api-scanner/src/test/resources/kotlin-lambdas/build.gradle
Update the API Scanner's Kotlin tests so that the Kotlin plugin also uses Gradle's new plugins DSL.
> Also use Gradle's plugins DSL for Kotlin tests.

- api-scanner/build.gradle
- api-scanner/src/main/java/net/corda/plugins/ScanApi.java
The new `java-gradle-plugin` means that the scanner no longer needs an explicit `compile` dependency on `gradleApi()`.
Also choose better Gradle annotations on the `ScanApi` task's properties so that Gradle understands how they are expected to be used.
> Increase the "Gradle-Fu" of the API Scanner plugin

- api-scanner/src/main/java/net/corda/plugins/ScanApi.java
- api-scanner/src/test/java/net/corda/plugins/KotlinVarargMethodTest.java
- api-scanner/src/test/java/net/corda/plugins/VarargMethodTest.java
- api-scanner/src/test/resources/kotlin-internal-annotation/build.gradle
- api-scanner/src/test/resources/kotlin-vararg-method/build.gradle
- api-scanner/src/test/resources/kotlin-vararg-method/kotlin/net/corda/example/KotlinVarargMethod.kt
- api-scanner/src/test/resources/vararg-method/build.gradle
- api-scanner/src/test/resources/vararg-method/java/net/corda/example/VarargMethod.java
- constants.properties
Methods with `vararg` parameters have an extra flag in the `.class` file. This flag has value 0x0080, which happens to be the same as `TRANSIENT` for fields.
_However_, the `java.lang.reflect.Modifier` class doesn't include this flag in the list of modifiers allowed for a method! We need to add this flag into the flag mask for methods.
> [CORDA-1148] Fix API Scanner not to exclude vararg methods.

- api-scanner/src/main/java/net/corda/plugins/ScanApi.java
I added this ordering in an attempt to make the implicit annotation ordering explicit. However, while the order that `fast-classpath-scanner` 2.7 returns class/interface annotations in is stable, it is not consistent with either the natural or the reverse ordering of the annotation class names.
We need to impose our own explicit ordering on these _and method_ annotations, but this should be done in a separate PR.
> Revert explicit ordering of class/interface annotations.

- api-scanner/src/main/java/net/corda/plugins/ScanApi.java
- api-scanner/src/test/java/net/corda/plugins/AnnotatedClassTest.java
- api-scanner/src/test/java/net/corda/plugins/AnnotatedInterfaceTest.java
- api-scanner/src/test/java/net/corda/plugins/AnnotatedMethodTest.java
- api-scanner/src/test/resources/annotated-class/java/net/corda/example/AlsoInherited.java
- api-scanner/src/test/resources/annotated-class/java/net/corda/example/HasInheritedAnnotation.java
- api-scanner/src/test/resources/annotated-interface/java/net/corda/example/AlsoInherited.java
- api-scanner/src/test/resources/annotated-interface/java/net/corda/example/HasInheritedAnnotation.java
- api-scanner/src/test/resources/annotated-method/java/net/corda/example/A.java
- api-scanner/src/test/resources/annotated-method/java/net/corda/example/B.java
- api-scanner/src/test/resources/annotated-method/java/net/corda/example/C.java
- api-scanner/src/test/resources/annotated-method/java/net/corda/example/HasAnnotatedMethod.java
The API Scanner currently writes `class`/`interface`/`method` annotations in the order they are returned from `fast-classpath-scanner:2.7`. While this ordering is stable, it is also an implementation detail of `fast-classpath-scanner` and so is likely to change in future versions. So we need to sort these annotations ourselves into ascending order.
**NOTE**: This change will require us to update `api-current.txt` in the Corda repository.
> [CORDA-1162] Sort class/interface/method annotations into ascending order.

- README.md
- constants.properties
4.0.5 has been released, so this is now 4.0.6-SNAPSHOT until we're ready to release 4.0.6.
> Update to 4.0.6-SNAPSHOT

- api-scanner/build.gradle
- api-scanner/src/test/java/net/corda/plugins/AnnotatedClassTest.java
- api-scanner/src/test/java/net/corda/plugins/AnnotatedFieldTest.java
- api-scanner/src/test/java/net/corda/plugins/AnnotatedInterfaceTest.java
- api-scanner/src/test/java/net/corda/plugins/AnnotatedMethodTest.java
- api-scanner/src/test/java/net/corda/plugins/BasicAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/BasicClassTest.java
- api-scanner/src/test/java/net/corda/plugins/BasicInterfaceTest.java
- api-scanner/src/test/java/net/corda/plugins/ClassWithInternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/ExtendedClassTest.java
- api-scanner/src/test/java/net/corda/plugins/ExtendedInterfaceTest.java
- api-scanner/src/test/java/net/corda/plugins/FieldWithInternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/InternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/InternalFieldTest.java
- api-scanner/src/test/java/net/corda/plugins/InternalMethodTest.java
- api-scanner/src/test/java/net/corda/plugins/InternalPackageTest.java
- api-scanner/src/test/java/net/corda/plugins/KotlinAnnotationsTest.java
- api-scanner/src/test/java/net/corda/plugins/KotlinInternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/KotlinLambdasTest.java
- api-scanner/src/test/java/net/corda/plugins/KotlinVarargMethodTest.java
- api-scanner/src/test/java/net/corda/plugins/MethodWithInternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/VarargMethodTest.java
- Use `Path` API instead of `File` with AssertJ.
- Ensure `kotlin-reflect` has been downloaded before the tests try to use it.
> Tidy the API scanner tests up slightly

- publish-utils/build.gradle
- publish-utils/src/main/groovy/net/corda/plugins/ProjectPublishExtension.groovy
- publish-utils/src/main/groovy/net/corda/plugins/PublishTasks.groovy
- publish-utils/src/main/resources/META-INF/gradle-plugins/net.corda.plugins.publish-utils.properties
Add an option to the `publish` extension so that we can choose not to publish the javadoc artifact.
Also upgrade the plugin to use `java-gradle-plugin` and fix some compiler warnings.
> Update publish-utils so that publishing javadoc is optional.

- changelog.md
- publish-utils/build.gradle
- publish-utils/src/main/groovy/net/corda/plugins/ProjectPublishExtension.groovy
- publish-utils/src/main/groovy/net/corda/plugins/PublishPlugin.groovy
- publish-utils/src/main/groovy/net/corda/plugins/Publisher.groovy
Refactor `publish-utils` to configure publication during the `afterEvaluate` handler.
> Remove the special nature of the publish-utils name property.

- api-scanner/build.gradle
- api-scanner/src/main/java/net/corda/plugins/ScanApi.java
- api-scanner/src/test/java/net/corda/plugins/KotlinAnnotationsTest.java
- changelog.md
The `@JvmStatic` annotation doesn't need to appear in the API output because it also causes the Kotlin compiler to generate `static final` modifiers. And it is only the `static final` modifiers that are important for the API.
This will allow us to improve the Java-friendliness of the API without the API Stability gate generating a lot of false-positives.
> CORDA-1224: Update API Scanner not to output `@JvmStatic` annotations.

- changelog.md
- cordapp/build.gradle
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/Utils.kt
- cordapp/src/main/resources/META-INF/gradle-plugins/net.corda.plugins.cordapp.properties
- quasar-utils/build.gradle
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- quasar-utils/src/main/resources/META-INF/gradle-plugins/net.corda.plugins.quasar-utils.properties
CorDapps are supposed to exclude `quasar-core` from their "fat jars". However, we have switched to a "jitpack" version of `quasar-core` which has `group=com.github.corda.quasar` instead of `group=co.paralleluniverse`. So extend the pattern-matching to handle jitpack artifacts in the `com.github.corda` namespace.
And while I'm here, fix some compiler warnings and upgrade the plugin to use `java-gradle-plugin`.
> CORDA-1301: Also exclude versions of dependencies that were created via jitpack.

- cordform-common/build.gradle
- cordformation/build.gradle
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- cordformation/src/main/resources/META-INF/gradle-plugins/net.corda.plugins.cordformation.properties
- cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
Resolves the following issues:
- Remove unused `import`s.
- Add `gradlePlugins` section to `build.gradle`.
- Declare simple `val` properties as `const`.
- Run Gradle test-kit with "--info" to provide better visibility for test failures.
- Configure tests to use host project's Gradle cache.
> Resolve issues in Cordformation code

- changelog.md
- cordapp/build.gradle
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordform-common/build.gradle
Replace deprecated kotlin-stdlib-jre8 artifact with kotlin-stdlib-jdk8.
> CORDA-1263: Replace deprecated Kotlin artifacts.

- build.gradle
Configure Gradle's wrapper via its extension, as we're supposed to.
> Simplify Gradle wrapper configuration.

- api-scanner/build.gradle
- api-scanner/src/test/java/net/corda/plugins/AnnotatedClassTest.java
- api-scanner/src/test/java/net/corda/plugins/AnnotatedFieldTest.java
- api-scanner/src/test/java/net/corda/plugins/AnnotatedInterfaceTest.java
- api-scanner/src/test/java/net/corda/plugins/AnnotatedMethodTest.java
- api-scanner/src/test/java/net/corda/plugins/BasicAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/BasicClassTest.java
- api-scanner/src/test/java/net/corda/plugins/BasicInterfaceTest.java
- api-scanner/src/test/java/net/corda/plugins/ClassWithInternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/CopyUtils.java
- api-scanner/src/test/java/net/corda/plugins/ExtendedClassTest.java
- api-scanner/src/test/java/net/corda/plugins/ExtendedInterfaceTest.java
- api-scanner/src/test/java/net/corda/plugins/FieldWithInternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/GradleProject.java
- api-scanner/src/test/java/net/corda/plugins/InternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/InternalFieldTest.java
- api-scanner/src/test/java/net/corda/plugins/InternalMethodTest.java
- api-scanner/src/test/java/net/corda/plugins/InternalPackageTest.java
- api-scanner/src/test/java/net/corda/plugins/KotlinAnnotationsTest.java
- api-scanner/src/test/java/net/corda/plugins/KotlinInternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/KotlinLambdasTest.java
- api-scanner/src/test/java/net/corda/plugins/KotlinVarargMethodTest.java
- api-scanner/src/test/java/net/corda/plugins/MethodWithInternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/VarargMethodTest.java
- api-scanner/src/test/resources/gradle.properties
Apply the JaCoCo plugin to the API Scanner's unit tests. Also simplify these unit tests with a JUnit rule-chain.
> Add JaCoCo support to the API Scanner.

- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
This is to enable multiple calls to deployNodes without doing a gradle clean.
> CORDA-1389: Delete the root nodes directory before initialising the nodes

- constants.properties
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
Jar file has been renamed from
`corda-R3.<version>-<component>.jar`
to
`corda-enterprise.<version>-<component>.jar`  
Other minor fix to incorrect package exclusion path.
> ENT-1871 Rebrand R3Corda to Corda Enterprise 

- changelog.md
- cordform-common/src/main/java/net/corda/cordform/CordformNode.java
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Cordform task adds `configFile` to the generated node.conf.
Gradle element `configFile` inside `node` is just an intermediate placeholder for the Gradle task, 
it was never used by the node as a property in node.conf.
A node strictly checks for allowed keys in node.conf and `configFile` is not allowed/accepted.
The change prevents 'leaking' `configFile` as node property.
> ENT-2059 Cordformation shouldn't add configFile property to node.conf

- changelog.md
- cordform-common/src/main/java/net/corda/cordform/CordformNode.java
- cordformation/src/main/kotlin/net/corda/plugins/Cordform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Cordform Gradle task can now copy jar files to `./driver` subdirectory relative to node directory. 
The list of file can be specified by `drivers` list in `node` element.
Using `ext.drivers` and `drivers = ext.drivers`in node element the  list reused for all nodes or concatenated to have both specific and common values.
Example:
`task deployNodes(type: net.corda.plugins.Cordform, dependsOn: ['jar']) {
...
node {
...
name "O=Notary Service,L=Zurich,C=CH"
drivers = ['/lib/jars/my_jar.jar']
...
}
}`
The file `my_jar.jar` will be placed into `Notary Service/driver` subdirectory.
> ENT-2035 Cordform copies files to drivers directory

- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
https://r3-cev.atlassian.net/browse/CORDA-1649
> [CORDA-1649]: Add default `quasar_version` and `quasar_group` to quasar-utils plugin, so it's not require to specify them manually.

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
A Gradle dependency can consist of several files (i.e. transitive dependencies), and some of those files may also belong to other dependencies. Ensure that we exclude _all_ files belonging to the `cordapp`, `cordaCompile` and `cordaRuntime` configurations from the CorDapp fat jar.
> CORDA-1807: Exclude all files of excluded Gradle dependencies from CorDapps.

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/Utils.kt
- quasar-utils/build.gradle
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
We aren't interested in the transitive dependencies of anything added to the `quasar` or `cordaRuntime` configurations. But the Quasar agent still needs its transitive dependencies on the runtime classpath or it won't be able to execute.
- Ensure that `quasar-core` is added to Gradle's `runtimeClasspath` configuration along with all of its transitive dependencies.
- Also add `quasar-core` to the `compileOnly` configuration so that (say) its `@Suspendable` and `Strand` classes are present on the compile classpath.
> CORDA-1832: Add transitive dependencies of Quasar agent to runtime configuration.

- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/Utils.kt
- cordapp/src/test/kotlin/net/corda/plugins/VersionComparatorTest.kt
This PR adds verfification of Gradle version that CorDapp is built with against the Gradle Wrapper config if one exists. This verification aims to save users from build-related issues if they use a wrong version of Gradle.
> Added gradle version check to the cordapp plugin

- build.gradle
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Elements.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/SanitisingTransformer.kt
Update JarFilter for the changes to Kotlin's metadata classes. Note that these classes are shaded and so JarFilter's only external Kotlin dependency is for `kotlin-stdlib-jdk8`.
> Upgrade to Kotlin 1.2.60.

- jar-filter/kotlin-metadata/build.gradle
Remove `dontwarn` rule which hasn't been necessary since at least Kotlin 1.2.5x.
> Remove unnecessary ProGuard "dontwarn" rule.

- changelog.md
- cordform-common/build.gradle
- cordform-common/src/main/java/net/corda/cordform/CordformNode.java
- cordform-common/src/main/java/net/corda/cordform/RpcSettings.java
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordapp.kt
- cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
A CordFormation project does not necessarily build a CorDapp itself. Add a new
```
nodeDefaults {}
```
block to the task, which defines initial configuration that will be applied to every node. Also enhance the `cordapp` block to support
```
deploy = {true | false}
```
This allows the DSL to declare the following:
```
nodeDefaults {
projectCordapp {
deploy = false
}
}
```
> CORDA-1889: Update CordFormation to make deploying itself as a CorDapp optional.

- build.gradle
- jar-filter/kotlin-metadata/build.gradle
Upgrade to [Kotlin 1.2.70](https://blog.jetbrains.com/kotlin/2018/09/kotlin-1-2-70-is-out/).
> CORDA-2015: Upgrade to Kotlin 1.2.70.

- build.gradle
- jar-filter/kotlin-metadata/build.gradle
Upgrade to Kotlin 1.2.71 which has [these fixes](https://github.com/JetBrains/kotlin/releases/tag/v1.2.71).
> CORDA-2024: Upgrade to Kotlin 1.2.71.

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/Utils.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
The Jolokia agent is a fat jar, so exclude any transitive dependencies it declares from the CorDapp.
Also fix some compiler warnings, and add an error message to a `require` statement.
> CORDA-2092: Remove duplicate Jolokia files from CorDapp fat jars

- build.gradle
- changelog.md
4.0.31 has been consumed testing CORDA-2101, so increase the version to 4.0.32-SNAPSHOT.
> Bump version to 4.0.32-SNAPSHOT

- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
Addition of the signJar Task running after jar task by CORDA-1915 has broken up-to-date validity of the first one. CorDapp signed by default caused Jar task to be always out-of-sync, the signJar task was overwriting the Jar task output, delete the signJar task and move signing as part of the Jar task so it's output is unchanged by other task.
> Fix Jar task's up-to-date validity broken by Jar signing task (CORDA-1915)

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteOverloadedFunctionTest.kt
- jar-filter/src/test/resources/delete-overloaded-function/build.gradle
- jar-filter/src/test/resources/delete-overloaded-function/kotlin/net/corda/gradle/HasOverloadedFunction.kt
Only delete lambda inner classes that correspond to deleted (synthetic) "annotations holder" methods. Default lambda parameters can be deleted by observing when their "enclosing methods" are deleted instead.
> CORDA-2171: Fix JarFilter deleting default lamba parameters for functions.

- cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
- cordapp/src/main/kotlin/net/corda/plugins/Signing.kt
- cordapp/src/main/kotlin/net/corda/plugins/SigningOptions.kt
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/main/kotlin/net/corda/plugins/KeyGenAndSigning.kt
- cordformation/src/main/kotlin/net/corda/plugins/KeyGenAndSigningOptions.kt
Functional change: 
for few main `signing.options` the plugin tries to get a value from the relevant system property if the option is not set in the configuration entry, the system property name is 'signing.' + option name.
Refactorings:
String refactored to constants as some of them are used multiple times.
Removing redundant methods named as relevant property, for simple types both conventions works out-of-box (`key "value"` and `key="value"`).
Added methods with Boolean parameter for options which are true|false to enable (`key value` and not only `key "value"`).
Replace one 'instance' of Groovy `Closure` with Gradle `Action`.
> Few signing options defaults to system properties first, then to hardcoded defaults (improvements for CORDA-1915).

- jar-filter/build.gradle
The `shadow` plugin knows how to publish a shaded jar, so use it.
> Leverage the shadow plugin's publish functionality.

- build.gradle
Enforce Gradle's API restriction for plugins written in Kotlin. No functional change.
> Restrict Kotlin API to match the one that Gradle uses.

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappExtension.kt
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/Sealing.kt
CORDA-2096 introduced obligatory JAR sealing when Jar is signed, create separate DSL entry `sealing` to allow disable sealing. Sealing is enabled by default.
```
cordapp {
signing {
//... 
} 
sealing {
enabled true
}
//...
}
> CORDA-2096 Cordapp JAR sealing is optional

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt
Simple changes for the `JarFilter` plugin:
- Log a warning when we exceed the maximum number of passes allowed through the filter.
- Inline `rethrowAsUncheckedException()` so that it doesn't appear in the exception stack trace.
> Small code-quality tweaks to JarFilter plugin.

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
The `JvmConstructorSignature` should never be `null` when we're filtering.
> Ensure JarFilter's matched constructor signature is never null.

- cordapp/src/main/kotlin/net/corda/plugins/CordappData.kt
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/test/resources/net/corda/plugins/CorDappWithContractAndWorflowInfo.gradle
- cordapp/src/test/resources/net/corda/plugins/CorDappWithContractInfo.gradle
- cordapp/src/test/resources/net/corda/plugins/CorDappWithInfoAll.gradle
- cordapp/src/test/resources/net/corda/plugins/CorDappWithWorkflowInfo.gradle
Corda code processes version identifiers as integers.
Enforce this in the cordapp metadata.
> CORDA-2414 Enforce CorDapp version identifier to be an integer.

- cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt
- cordapp/src/test/resources/settings.gradle
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterConfigurationTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterTimestampTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConfigurationTests.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixTimestampTest.kt
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/Utilities.groovy
- quasar-utils/src/test/resources/settings.gradle
Ensure that our Gradle test projects all have their own `settings.gradle` files.
Gradle 5.x will insist on this, so lay the groundwork now.
> Ensure that Gradle plugin tests have their own settings.gradle file.

- build.gradle
- changelog.md
Includes following changes:
- cordformation: deployNodes does not attempt to sign any JARs unless explicitly configured to do so using signing.enabled = true
- cordapp: enforce CorDapp workflow and contract version identifier metadata to be an integer.
- cordapp: relax cordapp metadata checking (warn on missing metadata rather than failing-fast).
This allows multi-module structured CorDapps to only define metadata for flows and/or contracts modules.
> Update changelog and publish 4.0.38

- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/DelegatedPom.kt
- cordapp/src/main/kotlin/net/corda/plugins/Utils.kt
We need to be _sure_ that Gradle has finished creating the entire project's dynamic tasks before we can reasonably expect to find any `GenerateMavenPom` tasks. Gradle provides the
```kotlin
withType(Class<S> type, Action<? super S> configureAction)
```
API for _precisely_ this purpose. (And I really should have remembered this before now  :man_facepalming:).
> Update cordapp plugin to modify GenerateMavenPom tasks once the task-graph is ready.

- build.gradle
- cordapp/build.gradle
- cordformation/build.gradle
- jar-filter/build.gradle
Gradle plugins written in Kotlin will use Gradle's own provided Kotlin libraries and so should not be published with dependencies on different ones.
> CORDA-2474: Remove Kotlin library from published POMs for Kotlin plugins.

- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
The CordFormation plugin currently uses the `main` runtime classpath for the Network Bootstrapper. While the Bootstrapper will _probably_ have been included via either the `cordaCompile` or `cordaRuntime` configurations, there is still no way for us to include any other jars such as a SLF4J logging back-end. So switch to using the `test` runtime classpath here, and ensure that we close the classloader afterwards.
> CORDA-2612: Use Network Bootstapper with test runtime classpath.

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/Utils.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
Adding Jolokia to `cordaRuntime` instead of `runtime` means that our `cordapp` Gradle plugin will no longer add the Jolokia classes to the CorDapp semi-fat jar.
> CORDA-2642: Cordformation now adds Jolokia agent to Gradle's cordaRuntime configuration.

- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
Remove any `SecurityProvider` instances installed by the Network Bootstrapper because the JVM cannot discard their classes until all references to them are destroyed. We also want to ensure that the Network Bootstrapper links consistently to everything inside the single `ClassLoader` provided by `cordformation`, and not to any `ClassLoader` from a previous `deployNodes` invocation.
Also revert the `deployNodes` task back to using the runtime classpath because none of the extra jars on the test runtime classpath is needed by the Bootstrapper. Any extra SLF4J backend can be added to the Gradle's `runtimeOnly` configuration.
> CORDA-2676: Unregister all SecurityProvider instances installed by Network Bootstrapper.

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/Utils.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
Add Jolokia agent to the `cordaRuntime` configuration to prevent the `cordapp` plugin from including it inside the CorDapp.
> CORDA-2699: Backport Jolokia fix to 4.0 branch.

- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
The `quasar-utils` plugin _requires_ that Gradle's `compile`, `compileOnly` and `runtime` configurations already exist, but these configurations are created by the `java` plugin. So apply the `java` plugin up-front to improve the user experience.
> CORDA-2713: Update quasar-utils to apply java plugin automatically.

- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
Some LICENSE files have extensions (such as .txt and .md), these should be excluded in the same way that LICENSE was excluded. Similarly for NOTICE, the file extension should not be considered when determining whether or not to include it in the JAR.
Note that I'm seeing a build failure when attempting to build it locally, but I'm seeing this error on `master` as well:
```
Included projects: [root project 'junit4380683632756613633']
> Configure project :
Evaluating root project 'junit4380683632756613633' using build file 'C:\Users\egeek\Development\r3\corda-gradle-plugins\cordformation\build\junit4380683632756613633\build.gradle'.
Compiling build file 'C:\Users\egeek\Development\r3\corda-gradle-plugins\cordformation\build\junit4380683632756613633\build.gradle' using …
```
> Some license and notice files have extensions

- api-scanner/src/main/java/net/corda/plugins/ApiScanner.java
- changelog.md
The API Scanner's `scanApi` task is failing in Gradle 5.x with this exception:
```
Caused by: org.gradle.api.internal.AbstractMutationGuard$IllegalMutationException: DefaultTaskContainer#withType(Class, Action) on task set cannot be executed in the current context.
at org.gradle.api.internal.AbstractMutationGuard.createIllegalStateException(AbstractMutationGuard.java:39)
...
```
Modify this task to work in _both_ Gradle 4.x _and_ Gradle 5.x.
> CORDA-2889: Fix scanApi task configuration for Gradle 5.x.

- api-scanner/src/main/java/net/corda/plugins/ApiScanner.java
- changelog.md
The API Scanner's `scanApi` task is failing in Gradle 5.x with this exception:
```
Caused by: org.gradle.api.internal.AbstractMutationGuard$IllegalMutationException: DefaultTaskContainer#withType(Class, Action) on task set cannot be executed in the current context.
at org.gradle.api.internal.AbstractMutationGuard.createIllegalStateException(AbstractMutationGuard.java:39)
...
```
Modify this task to work in _both_ Gradle 4.x _and_ Gradle 5.x.
> CORDA-2889: Fix scanApi task configuration for Gradle 5.x. (#183)

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterAnnotations.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterConfigurationTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterProject.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterTimestampTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConfigurationTests.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorDefaultParameterTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFunctionDefaultParameterTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixProject.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixTimestampTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseDeleteConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseStubConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/UtilsTest.kt
JarFilter "gets away" with using POJOs for configuring its tasks at the moment, but Gradle 4.x onwards provides `Property` and `Provider` classes to do this properly. Update JarFilter accordingly.
> CORDA-2897: Update JarFilter to use Gradle Property and Provider classes.

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
Configure the CorDapp's jar task to remove the file timestamps from the jar's contents, and also to make the file order inside the jar reproducible. This make's Corda's CanonicalizerPlugin script obsolete.
> CORDA-2902: Remove file timestamps from contents of CorDapps.

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
Configure the CorDapp's jar task to remove the file timestamps from the jar's contents, and also to make the file order inside the jar reproducible. This make's Corda's CanonicalizerPlugin script obsolete.
>  CORDA-2902: Remove file timestamps from contents of CorDapps.

- changelog.md
- cordformation/build.gradle
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordapp.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
- cordformation/src/main/kotlin/net/corda/plugins/NetworkParameterOverrides.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- cordformation/src/main/kotlin/net/corda/plugins/PackageOwnership.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/NetworkParameterOverridesTest.kt
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
[CORDA-2491](https://r3-cev.atlassian.net/browse/CORDA-2491)
- Added `NetworkParameterOverrides` and `PackageOwnership` support. These are optional fields.
- The old entrypoint will still be used when no `networkParameterOverrides` is set.
- Updated `CordformTest`, which was still targeting Corda 3. Given the circular dependencies between `Cordformation` and Corda, these tests are only relying on released artifacts when testing for backwards compatibility or deploying the finance application. The tests have been updated so it is easier to run manually, targeting locally installed `SNAPSHOT` versions of the dependencies.
- Annotated existing members to make a better usage of incremental builds.
Example:
```
task deployNodes(type: net.corda.plugins.Cordform) {
networkParameterOverrides { …
```
> CORDA-2491 Add network parameter overrides to CordFormation

- build.gradle
Create the special POM artifact so that we can publish our Gradle plugins to a Maven repository and import them using the `plugins{}` block.
> CORDA-2903: Publish special POM tag to support Gradle plugins block.

- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/test/kotlin/net/corda/plugins/CordappGradleConfigurationsTest.kt
- cordapp/src/test/kotlin/net/corda/plugins/GradleProject.kt
- cordapp/src/test/kotlin/net/corda/plugins/PomFilterTest.kt
- cordapp/src/test/resources/gradle.properties
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
This behaviour is tricky and under-documented, so add some unit tests for it. We need to know what we might be breaking some day.
And applying the `java` plugin automatically in `cordformation` just means that `cordformation` won't break with an incomprehensible error message if `java` hasn't been applied already. (`quasar-utils` and `cordapp` both do this too.)
> CORDA-2907: Add test cases for CorDapp semi-fat jar Gradle configurations.

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
Use directoryProperty() that is initialised by a Provider - no need for a lambda.
> CORDA-2897: Simplify JarFilter's usage of directoryProperty().

- changelog.md
The fact that the `cordapp` plugin ignores the `runtimeOnly` configuration is a bug, not a feature! Don't tell users to use `runtimeOnly` like this!
> CORDA-2905: Tell users to use cordaRuntime instead of runtimeOnly.

- cordapp/src/test/kotlin/net/corda/plugins/CordappGradleConfigurationsTest.kt
- cordapp/src/test/kotlin/net/corda/plugins/GradleProject.kt
- cordapp/src/test/kotlin/net/corda/plugins/PomFilterTest.kt
- cordapp/src/test/resources/gradle.properties
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
* Add test cases for CorDapp semi-fat jar Gradle configurations.
* Remove explicit `java` plugin from Cordformation test cases, as it's no longer required.
> CORDA-2907: Add test cases for CorDapp semi-fat jar Gradle configurations. (#193)

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
Removing file timestamps from the jar's contents is not enough. We also need to specify file and directory permission bits explicitly, and then set every other option which may alter the jar output.
> CORDA-2915: Configure the CorDapp Jar task to create a stable SHA256 hash.

- api-scanner/build.gradle
- build.gradle
- cordapp/build.gradle
- cordapp/src/test/kotlin/net/corda/plugins/CordappGradleConfigurationsTest.kt
- cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt
- cordapp/src/test/kotlin/net/corda/plugins/GradleProject.kt
- cordapp/src/test/kotlin/net/corda/plugins/PomFilterTest.kt
- cordapp/src/test/kotlin/net/corda/plugins/Utilities.kt
- cordapp/src/test/kotlin/net/corda/plugins/VersionComparatorTest.kt
- cordformation/build.gradle
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/NetworkParameterOverridesTest.kt
- jar-filter/build.gradle
- quasar-utils/build.gradle
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/Utilities.groovy
All plugin modules now use Gradle's `useJUnitPlatform()`, although some modules are still using the "vintage" test engine.
> CORDA-2917: Preliminary migration to JUnit 5.

- cordapp/src/test/kotlin/net/corda/plugins/GradleProject.kt
Restore `println()` for now, because the HTML report generator will use it.
> CORDA-2917: Restore stdout to JUnit HTML report.

- CONTRIBUTORS.md
- changelog.md
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarExtension.groovy
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/Utilities.groovy
- quasar-utils/src/test/resources/src/test/java/BasicTest.java
Create a `quasar` Gradle extension to configure which packages should not be instrumented by the Quasar agent at runtime. Ideally, the `quasar_group` and `quasar_version` project properties should also be migrated to this extension in due course.
> Replace `quasar_exclusions` project property with a `quasar` extension.

- quasar-utils/src/main/groovy/net/corda/plugins/QuasarExtension.groovy
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
Restore the `quasar_exclusions` Gradle property and use it to initialise the `quasar` extension. This enables us to declare the package exclusions only once, while still allowing us to customise them per sub-project.
> CORDA-2948: Restore quasar_exclusions Gradle property for initial configuration values.

- api-scanner/build.gradle
- build.gradle
- cordapp/build.gradle
- cordformation/build.gradle
- jar-filter/build.gradle
- quasar-utils/build.gradle
The JUnit5 platform launcher is packaged as part of Gradle.
> CORDA-2917: Simplify use of JUnit 5 by removing platform launcher dependency.

- changelog.md
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
The Quasar agent is a fat jar and doesn't need anything else to be added to the runtime classpath.
> CORDA-2955: Remove Quasar's transitive dependencies from Gradle's runtime classpath.

- changelog.md
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
Instrumented code needs these transitive dependencies at runtime.
> CORDA-2955: Revert 710651d8b0f85dd283b3ddf793aae9f62b054795.

- build.gradle
Update the Gradle plugin publishing so that:
- We generate each plugin's tag based correctly on the plugin ID.
- We allow a plugin bundle to contain more than one plugin.
> CORDA-2903: Tweak build script to replicate automatedPublishing better.

- build.gradle
- jar-filter/README.md
- jar-filter/build.gradle
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Elements.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/KotlinAwareVisitor.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerVisitor.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/SanitisingTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterProject.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFieldValPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFieldVarPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixProject.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/AsmTools.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/ClassMetadata.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/FileMetadata.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/MetadataTools.kt
Stop using Kotlin's internal ProtoBuf classes to manipulate the `kotlin.Metadata` annotations. Use the `kotlin-metadata-jvm` artifact's new API to do this instead.
> CORDA-3013: Modify JarFilter to update Kotlin metadata via public API.

- changelog.md
- publish-utils/src/main/groovy/net/corda/plugins/MavenMapper.groovy
- publish-utils/src/main/groovy/net/corda/plugins/ProjectPublishExtension.groovy
- publish-utils/src/main/groovy/net/corda/plugins/PublishTasks.groovy
Allow publish-utils to choose suitable Maven scopes when publishing dependencies from a given Gradle configuration. This will allow us to generate a POM for `corda-core-deterministic` that will work correctly in Gradle 5.x.
This change enhances the
```gradle
publish {
dependenciesFrom configurationName
}
```
functionality, which is used mainly by the deterministic artifacts.
> CORDA-3026: Allow publish-utils to choose suitable Maven scopes.

- publish-utils/src/main/groovy/net/corda/plugins/MavenMapper.groovy
Earlier versions of Groovy seem less able to compute an inferred type. Forward port this fix from the release-4.0 branch to keep the two branches aligned.
> Groovy tweak to MavenMapper for compatibility with earlier versions.

- cordapp/src/test/kotlin/net/corda/plugins/CordappLibraryGradleConfigurationsTest.kt
Document the current behaviour better so that we know how implementing CORDA-2905 will change it.
> CORDA-2907: Extend test cases for CorDapp semi-fat jar behaviour.

- cordapp/src/test/kotlin/net/corda/plugins/CordappLibraryGradleConfigurationsTest.kt
Document the current behaviour better so that we know how implementing CORDA-2905 will change it.
Test how the `cordapp` plugin behaves with the `java-library` plugin and its `api` and `implementation` configurations.
> CORDA-2907: Extend test cases for CorDapp semi-fat jar behaviour. (#241)

- publish-utils/src/main/groovy/net/corda/plugins/MavenMapper.groovy
Using `@CompileStatic` on `MavenMapper` in the `publish-utils` plugin has unintended side-effects.
More specifically, the compiled byte-code seems to misbehave when executed by later versions of Groovy/Gradle.
Remove it!
> Remove @CompileStatic from MavenMapper in publish-utils.

- changelog.md
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarExtension.groovy
- quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
- quasar-utils/src/test/resources/repositories.gradle
This adds an `excludeClassLoaders = []` option to the `quasar` extension. Currently, only Quasar 0.7.12_r3 and above (excluding 0.8.0) supports this.
> CORDA-3228: Update Quasar utils plugin to support excluding classloaders.

- build.gradle
- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- cordformation/src/main/resources/net/corda/plugins/runnodes
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
* `cordformation`: remove hard dependency on java 1.8 for macos in runnodes (and allow for usage of JAVA_HOME if set)
* `cordformation`: add support for classifier (eg. jdk11) in detection of corda runtime artifacts (eg. corda.jar, test-server.jar).
> CORDA-3224 Java 11 support tweaks.

- CONTRIBUTORS.md
- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle
Add support for `OU` when generating node directories in cordformation. This is to prevent duplicate organizations from overwriting the node directory.
Also fixed a couple small issues relative to trim / regex handling.
First PR so please let me know if anything else is required on my end.
- [n/a] If you added/changed public APIs, did you write/update the JavaDocs?
Thanks for your code, it's appreciated! :)
> enhance node dirname parsing to include OU and fix trim

- api-scanner/src/main/java/net/corda/plugins/ApiScanner.java
- api-scanner/src/main/java/net/corda/plugins/ScannerExtension.java
- api-scanner/src/test/java/net/corda/plugins/GenerateEmptyApiTest.java
- api-scanner/src/test/java/net/corda/plugins/GenerateScanClassifierTest.java
- api-scanner/src/test/java/net/corda/plugins/GenerateScanPropertyClassifierTest.java
- api-scanner/src/test/java/net/corda/plugins/GenerateScanWrongClassifierTest.java
- api-scanner/src/test/java/net/corda/plugins/GradleProject.java
- api-scanner/src/test/resources/generate-scan-classifier/build.gradle
- api-scanner/src/test/resources/generate-scan-classifier/java/net/corda/example/WhenScanHasClassifier.java
- api-scanner/src/test/resources/generate-scan-property-classifier/build.gradle
- api-scanner/src/test/resources/generate-scan-property-classifier/java/net/corda/example/WhenScanHasPropertyClassifier.java
- api-scanner/src/test/resources/generate-scan-wrong-classifier/build.gradle
- api-scanner/src/test/resources/generate-scan-wrong-classifier/java/net/corda/example/WhenScanHasWrongClassifier.java
- changelog.md
Enable the `scanApi` task to target a jar task that has a specific `archiveClassifier` value, rather than only scanning the jar that has no `archiveClassifier`.
This will ensure that we can still generate the public API when building with Java 11.
> CORDA-3327: Configure API Scanner plugin to scan jar with specific classifier.

- api-scanner/build.gradle
- build.gradle
- cordapp/build.gradle
- cordapp/src/test/kotlin/net/corda/plugins/CordappGradleConfigurationsTest.kt
- cordapp/src/test/kotlin/net/corda/plugins/CordappLibraryGradleConfigurationsTest.kt
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
- jar-filter/build.gradle
- jar-filter/src/test/resources/repositories.gradle
- jar-filter/unwanteds/build.gradle
- Remove the `jcenter` repository  because `mavenCentral` has a longer memory.
- Remove the Jitpack repository because it is (and should be!) unused.
- Replace the stale reference to Corda 5.0-SNAPSHOT with 4.2
> Maintenance on Gradle files.

- api-scanner/src/main/java/net/corda/plugins/ScanApi.java
There's no need to filter the method annotations because the annotation information is entirely separate from the method name and type descriptor.
> Remove irrelevant annotation processing when filtering methods.

- api-scanner/README.md
- api-scanner/src/main/java/net/corda/plugins/ApiPrintWriter.java
- api-scanner/src/main/java/net/corda/plugins/ApiScanner.java
- api-scanner/src/main/java/net/corda/plugins/ScanApi.java
- api-scanner/src/main/java/net/corda/plugins/ScannerExtension.java
- api-scanner/src/test/java/net/corda/plugins/ClassWithInternalAnnotationTest.java
- api-scanner/src/test/java/net/corda/plugins/ExcludePackageTest.java
- api-scanner/src/test/resources/class-internal-annotation/java/net/corda/example/AnnotatedClass.java
- api-scanner/src/test/resources/class-internal-annotation/java/net/corda/example/InternalClass.java
- api-scanner/src/test/resources/exclude-package/build.gradle
- api-scanner/src/test/resources/exclude-package/java/net/corda/example/unwanted/UnwantedClass.java
- api-scanner/src/test/resources/exclude-package/java/net/corda/example/unwanted/very/VeryUnwantedClass.java
- api-scanner/src/test/resources/exclude-package/java/net/corda/example/wanted/WantedClass.java
- changelog.md
Add `excludePackages` to the API Scanner plugin's DSL. This is so that it can ignore all of the classes in the DJVM's `sandbox.**` packages.
I've also simplified some of the code to make it easier to upgrade to ClassGraph.
> CORDA-3377: Add `excludePackages` to the `scanApi` task.

- changelog.md
- publish-utils/src/main/groovy/net/corda/plugins/MavenMapper.groovy
The code incorrectly assumes that dependencies returned from `Configuration.getAllDependencies()` will always have a non-null `group` and `version`. Apply a filter to remove any unusable entries.
> CORDA-3453: Fix NPE in publish-utils when publishing dependencies from a custom Gradle configuration.

- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Apply Gradle's task property annotations more correctly, and make some of the property setters non-public too.
> CORDA-3586: Fix Gradle task validation warnings for cordformation.

- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Apply Gradle's task property annotations more correctly, and make some of the property setters non-public too.
Unfortunately, some of these warnings are unfixable in Gradle 4.x.
> CORDA-3586: Backport fixes for Gradle cordformation task validation warnings.

- api-scanner/build.gradle
- api-scanner/src/main/java/net/corda/plugins/GenerateApi.java
- api-scanner/src/main/java/net/corda/plugins/ScanApi.java
- cordapp/build.gradle
- cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
- cordformation/build.gradle
- cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
- jar-filter/build.gradle
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
- jar-filter/unwanteds/build.gradle
- publish-utils/build.gradle
- Use the `plugins` DSL better.
- Apply `@PathSensitive` annotations to file input properties.
> BACKPORT: Tidy up usage of Gradle API.

- api-scanner/src/test/resources/gradle.properties
- cordapp/src/test/resources/gradle.properties
- cordformation/src/test/resources/gradle.properties
- jar-filter/src/test/resources/gradle.properties
- quasar-utils/src/test/resources/gradle.properties
- Disable Gradle's cache for all tests.
- Configure JVM for each `GradleRunner` with 512 MB of memory.
> NOTICK: Configure properties for Gradle test projects.

- CONTRIBUTORS.md
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
The database url that is specified in extraConfig in the node configuration like this:
```
extraConfig = [
dataSourceProperties: [
dataSourceClassName: "org.postgresql.ds.PGSimpleDataSource",
'dataSource.url': "jdbc:postgresql://localhost:5434/postgres",
'dataSource.user': "postgres",
'dataSource.password': "password"
],
database: [
transactionIsolationLevel : "READ_COMMITTED"
]
]
```
is overridden by the default h2 url.
PR fixes this override. 
Agree.
Thanks for your code, it's appreciated! :)
> Fix data source url override

- CONTRIBUTORS.md
- cordapp/build.gradle
- cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt
- cordformation/build.gradle
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
`IOUtils.copy` doesn't close the output stream which means that needs to be used inside a **try/finally** block (or **try-with-resource** in Java or **use** block in Kotlin)
The way it was used in the unit test was simply leaking an opened file descriptor with possible unwanted side effects; it actually calls `flush` before exiting, which is the reason why nothing bad happens, but it still doesn't look quite right. In Windows for example you cannot delete a file while it is opened by another process, which is something that could happen here since the unit tests create temporary directories that are deleted afterwards, and there is no synchronization between the leaked `FileOutputStream`s closing (which at this point depends entirely on the garbage collector's mood) and the temporary …
> replaced `org.apache.commons.io.IOUtils` with `java.nio.file.Files`

- CONTRIBUTORS.md
- changelog.md
- cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
This allows runnodes to use screen as an alternative to osascript on macOS. screen is included in macOS making it an easy alternative to use.
The change behaves the same as tmux support on Linux. If the user is already running screen, it will be used; otherwise it will run osascript like normal.
> Use screen on macOS when the user is already running screen

- CONTRIBUTORS.md
- build.gradle
- changelog.md
- cordformation/build.gradle
- cordformation/src/main/kotlin/net/corda/plugins/DockerImage.kt
- cordformation/src/test/kotlin/net/corda/plugins/DockerImageTest.kt
- cordformation/src/test/resources/net/corda/plugins/DeployDockerImage.gradle
This task has been added to allow users to quickly create a docker image based on their cordapp. 
The inputs are BaseImage & trustRootStoreName
BaseImage is the the image you wish to use as the base Corda image for your docker image.
This has three enum values to make life easier for end user : zulu, corretto and enterprise. 
This value defaults to Zulu
The TrustRootStoreName is to allow users to embed a trust root into their corda docker image so they can join an external network. 
The expectation is it will be in the project directory.
>  EG-153/jmacmahon/dockerfileplugin

- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/ConfigurationUtils.kt
- cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- cordformation/src/main/kotlin/net/corda/plugins/RpcSettings.kt
- cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/ConfigurationUtilsTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/DockerformTest.kt
- cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithDocker.gradle
Dockerform allocates predefined port numbers instead of using the ones specified in the `node.conf`. Users should be allowed to specify those ports
> EG-1856: Allow users to specify Dockerform ports

- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExtraCommandForDbSchema.gradle
In Corda 4.6, database schema migration/set-up will have to be run explicitly via a new subcommand - this change brings in the code to do this during cordformation, currently guarded behind a property that defaults to off.
> ENT-5258 Handle db migration in Cordform

- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
This change allows ACCEPT_LICENSE environment variable to be passed to the Corda Docker Image. This variable is important for the ENT version and has no effect on the OS version.
> ENT-5364: Added ACCEPT_LICENSE environment variable

- cordformation/src/test/resources/gradle.properties
- cordformation/src/test/resources/net/corda/plugins/DeployDockerImage.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
- Use common `gradle.properties` instead of `buildscript` wherever possible.
- Replace deprecated `runtime` configuration with `cordaRuntime`
- Provide simple SLF4J implementation for Network Bootstrapper.
> NOTICK: Make Gradle scripts for cordformation tests consistent.

- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExtraCommandForDbSchema.gradle
Add cmd line paramters to the runMigrationScripts job so that the node creates all the app and core schemas as part of the bootstrapping in CordFormation.
> ENT-5316 Add extra parameters for app and core schema

- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/main/kotlin/net/corda/plugins/NetworkParameterOverrides.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
extended `NetworkParameterOverrides` object to support `minimumPlatformVersion`, `maxMessageSize`, `maxTransactionSize` and `eventHorizon`
> [CORDA-3829] extended NetworkParameterOverrides object

- cordformation/src/main/kotlin/net/corda/plugins/NetworkParameterOverrides.kt
Annotate `NetworkParameterOverrides.isEmpty()` as `@Internal` to prevent Gradle mistaking it for a new task property.
> CORDA-3829: Annotate NetworkParameterOverrides.isEmpty as internal.

- cordapp/src/main/kotlin/net/corda/plugins/CordappData.kt
- cordapp/src/main/kotlin/net/corda/plugins/CordappExtension.kt
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/Info.kt
- cordapp/src/main/kotlin/net/corda/plugins/Sealing.kt
- cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
- cordapp/src/main/kotlin/net/corda/plugins/Signing.kt
- cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt
- cordapp/src/test/resources/net/corda/plugins/CorDappWithContractAndWorflowInfo.gradle
- cordapp/src/test/resources/net/corda/plugins/CorDappWithContractInfo.gradle
- cordapp/src/test/resources/net/corda/plugins/CorDappWithInfo.gradle
- cordapp/src/test/resources/net/corda/plugins/CorDappWithInfoAll.gradle
- cordapp/src/test/resources/net/corda/plugins/CorDappWithWorkflowInfo.gradle
- cordapp/src/test/resources/net/corda/plugins/CorDappWithoutMetadata.gradle
Update the `cordapp` plugin to use Gradle's "lazy" property APIs. This fixes some technical debt, and should have no functional impact.
Note: Gradle considers a `Property` to be "present" if `get()` will return a value, _and this includes having a value set by `convention()`_. This doesn't include setting a `Provider` as a `convention()` if that `Provider` also has no value.
> CORDA-3838: Make cordapp plugin properties lazy.

- cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
We must "get" the value of the `SignJar` task's `postfix` property before using it.
> CORDA-3838: Fix generated name of signed CorDapp jar.

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
Ensure that we close every `InputStream` created for the JAR file entries we are scanning. This is just good housekeeping, but otherwise we _could_ theoretically run out of file descriptors if required to scan a particularly large JAR.
> NOTICK: Close input streams as JarFilter scans jar entries.

- .ci/Jenkinsfile
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
Ensure that we close every `InputStream` created for the JAR file entries we are scanning. This is just good housekeeping, but otherwise we could theoretically run out of file descriptors if required to scan a particularly large JAR.
> NOTICK: Close input streams as JarFilter scans jar entries. (#318)

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/CordappUtils.kt
Bring the `cordapp` plugin's internal Gradle version check up-to-date for the 5.x release.
Also tidy up the Kotlin for the version-checking function.
The specific Gradle 5.1 API is:
```java
/**
* Specifies the provider of the value to use as the convention for this property. The convention is used when no value has been set for this property.
*
* @param valueProvider The provider of the value.
* @return this
* @since 5.1
*/
Property<T> convention(Provider<? extends T> valueProvider);
```
> CORDA-3860: Raise minimum Gradle version for cordapp plugin to v5.1.

- changelog.md
- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishTasks.groovy
Update `publish-utils` to create the following tasks lazily:
- `sourceJar`
- `javadocJar`
- `install`
This means that Gradle will not configure them unless it also intends to execute them.
Also tweak the logging to use SLF4J place-holders rather than string concatenation.
> CORDA-3876: Update publish-utils to use lazy task configuration where possible.

- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/CordappUtils.kt
This is not a user-visible change, unless you perform a build scan on your Gradle project. The `configureEach {}` API was introduced in Gradle 4.9.
> CORDA-3884: Use Gradle's task configuration avoidance APIs for cordapp.

- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishExtension.groovy
This will allow us to use Gradle's task configuration avoidance by writing:
```groovy
def jar = tasks.named('jar', Jar)
publish {
name jar.flatMap { it.archiveBaseName }
}
```
instead of
```groovy
publish {
name jar.baseName
}
```
> CORDA-3902: Allow publish.name to be set using Gradle provider.

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterAnnotations.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
Prevent JarFilter tasks from recalculating the names of their output files every single time.
> CORDA-3884: Update JarFilter's usage of FileCollection for Gradle 5.6.

- README.md
- api-scanner/README.md
- api-scanner/annotations/build.gradle
- api-scanner/src/main/java/net/corda/plugins/apiscanner/ApiPrintWriter.java
- api-scanner/src/main/java/net/corda/plugins/apiscanner/ApiScanner.java
- api-scanner/src/main/java/net/corda/plugins/apiscanner/GenerateApi.java
- api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java
- api-scanner/src/main/java/net/corda/plugins/apiscanner/ScannerExtension.java
- api-scanner/src/test/java/net/corda/plugins/apiscanner/CopyUtils.java
- api-scanner/src/test/java/net/corda/plugins/apiscanner/GenerateChildProjectTest.java
- api-scanner/src/test/java/net/corda/plugins/apiscanner/GenerateNoScanTest.java
- api-scanner/src/test/java/net/corda/plugins/apiscanner/GradleProject.java
- api-scanner/src/test/java/net/corda/plugins/apiscanner/KotlinExcludeMethodTest.java
- api-scanner/src/test/resources/generate-child-project/build.gradle
- api-scanner/src/test/resources/generate-child-project/child-project/build.gradle
- api-scanner/src/test/resources/generate-child-project/child-project/java/net/corda/example/ChildClass.java
- api-scanner/src/test/resources/generate-child-project/settings.gradle
- api-scanner/src/test/resources/generate-no-scan/build.gradle
- api-scanner/src/test/resources/kotlin-annotations/build.gradle
- api-scanner/src/test/resources/kotlin-auto-generated-class/build.gradle
- api-scanner/src/test/resources/kotlin-constant/build.gradle
- api-scanner/src/test/resources/kotlin-enum/build.gradle
- api-scanner/src/test/resources/kotlin-exclude-method/build.gradle
- api-scanner/src/test/resources/kotlin-internal-annotation/build.gradle
- api-scanner/src/test/resources/kotlin-lambdas/build.gradle
- api-scanner/src/test/resources/kotlin-legacy/build.gradle
- api-scanner/src/test/resources/kotlin-library/build.gradle
- api-scanner/src/test/resources/kotlin-vararg-method/build.gradle
- Migrate task properties to be "lazy".
- Avoid configuring tasks that will not be executed.
- Implicitly apply the `java` plugin up front.
- Increase unit test coverage for `GenerateApi` task.
- This plugin now requires Gradle 5.6+.
> CORDA-3884: Address some technical debt in the API Scanner plugin.

- README.md
- cordapp/src/test/kotlin/net/corda/plugins/CordappGradleConfigurationsTest.kt
- cordapp/src/test/kotlin/net/corda/plugins/CordappLibraryGradleConfigurationsTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/Utilities.kt
Windows cannot delete an open file, so ensure that instances of `ZipFile` used in the tests are always closed.
And mention the `DockerImage` task in the README too - it can't hurt :wink:.
> NOTICK: Ensure that ZipFiles used for testing are always closed afterwards.

- publish-utils/src/main/groovy/net/corda/plugins/publish/MavenMapper.groovy
- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishConfigurationProjectListener.groovy
- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishPlugin.groovy
Only install `PublishConfigurationProjectListener` for the root project, and allow it to listen for all other projects.
> CORDA-3884: Refactor publish-utils to use a single root project listener.

- cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/DockerformTest.kt
- cordformation/src/test/resources/net/corda/plugins/DeployDockerImage.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithNetworkConfigWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExternalDBSettingsWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExtraCommandForDbSchema.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
- cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithNetworkConfigWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithDocker.gradle
Windows cannot delete open files, so ensure that streams and reader objects created during the tests are closed afterwards.
Also fix some trivial compiler warnings, and ensure that Network Bootstrapper has a simple SLF4J back-end available for the `cordformation` tests.
> NOTICK: Close open files to prevent test failures on Windows.

- cordformation/build.gradle
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/DockerImageTest.kt
- cordformation/src/test/resources/gradle.properties
- cordformation/src/test/resources/net/corda/plugins/DeployDockerImage.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExtraCommandForDbSchema.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
- gradle.properties
- jar-filter/build.gradle
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteFunctionTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteOverloadedFunctionTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterConfigurationTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConfigurationTests.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFieldValPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFieldVarPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFunctionDefaultParameterTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFunctionTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixValPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixVarPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseDeleteConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseStubConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/StubFunctionOutTest.kt
- jar-filter/src/test/resources/gradle.properties
- jar-filter/src/test/resources/stub-function/build.gradle
- `javax.annotation-api` must be included separately with JDK11.
- `Class.newInstance()` is deprecated in favour of `Class.getDeclaredConstructor().newInstance()`.
- Test using Corda 4.3 artifacts, which has preliminary Java 11 support.
- `ZipFile` throws `NoSuchFileException` instead of `FileNotFoundException` on Java 11.
> NOTICK: Fix basic warnings and errors when building on JDK11.

- api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java
Gradle doesn't recognise `isXXX()` as a getter method for a bean, so replace with `getXXX()`.
> NOTICK: Fix "deprecated in Gradle 7.x" warning for API Scanner.

- build.gradle
Publishing this extra POM artifact for each plugin allows us to download the Corda Gradle plugins from Artifactory via Gradle's `plugins` block.
> NOTICK: Publish the Gradle plugin marker to Artifactory.

- build.gradle
Publishing this extra POM artifact for each plugin allows us to download the Corda Gradle plugins from Artifactory via Gradle's `plugins` block.
> NOTICK: Publish the Gradle plugin marker to Artifactory. (#349)

- publish-utils/src/main/groovy/net/corda/plugins/publish/MavenMapper.groovy
- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishConfigurationProjectListener.groovy
- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishPlugin.groovy
Also resolve warnings about deprecated Gradle API usage in `publish-utils`.
> NOTICK: Use Gradle lazy task configuration when publishing sources and javadoc.

- changelog.md
- gradle.properties
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerVisitor.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/SanitisingTransformer.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteNestedClassTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/MetadataTools.kt
- jar-filter/src/test/resources/annotations/java/net/corda/gradle/jarfilter/DeleteJava.java
- jar-filter/src/test/resources/delete-nested-class/build.gradle
- jar-filter/src/test/resources/delete-nested-class/java/net/corda/gradle/DeletedOuterClass.java
- jar-filter/src/test/resources/delete-nested-class/java/net/corda/gradle/OuterClass.java
ASM 8 includes support for JDK11's nest host and nest member byte-code elements.
> CORDA-4060: Upgrade JarFilter to use ASM 8.0.1.

- changelog.md
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
Adding a Gradle configuration as a dependency is deprecated as of Gradle 6.7.
> CORDA-4061: Resolve warning in quasar-utils about deprecated Gradle API.

- changelog.md
- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishConfigurationProjectListener.groovy
- publish-utils/src/main/groovy/net/corda/plugins/publish/bintray/Developer.groovy
We may need to repackage some artifacts for republishing into Artifactory, and these artifacts may not have such things as a "developer email address". Make the "developers" section optional.
> NOTICK: Allow publishing without developer information.

- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishPlugin.groovy
Do not always apply `JavaPlugin` so that we can then create the `sources` and `javadocJar` tasks. Rather, only create these tasks if/when `JavaPlugin` is applied.
> NOTICK: Only create the source/javadoc tasks if the Java plugin is applied.

- changelog.md
- gradle.properties
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerVisitor.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/SanitisingTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteJava15PermittedSubclassTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteJava15SealedClassTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/MetadataTools.kt
- jar-filter/src/test/resources/delete-java15-permitted-subclass/build.gradle
- jar-filter/src/test/resources/delete-java15-permitted-subclass/java/net/corda/gradle/UnwantedSubclass.java
- jar-filter/src/test/resources/delete-java15-permitted-subclass/java/net/corda/gradle/WantedSealedClass.java
- jar-filter/src/test/resources/delete-java15-permitted-subclass/java/net/corda/gradle/WantedSubclass.java
- jar-filter/src/test/resources/delete-java15-sealed-class/build.gradle
- jar-filter/src/test/resources/delete-java15-sealed-class/java/net/corda/gradle/DeletableSealedClass.java
- jar-filter/src/test/resources/delete-java15-sealed-class/java/net/corda/gradle/SealedSubclass.java
Leverages ASM's support for `Permitted Subclasses`, but `record` support will require deeper study.
> CORE-830: Upgrade JarFilter to use ASM 9.0.

- changelog.md
- cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
- cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt
Replace the key and store password with `****` when logging the signing options.
This fixes #303.
> CORE-853: Do not log passwords when signing CorDapp jars.

- changelog.md
- gradle.properties
Start development of 5.0.14 on the new `release/5.0` branch.
> Begin 5.0.14-SNAPSHOT.

- api-scanner/src/main/java/net/corda/plugins/apiscanner/GenerateApi.java
- api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java
We cannot finalize property values before their tasks have executed. Gradle 7,x will reject such behaviour as an error, so fix it now.
> NOTICK: Resolve Gradle deprecation warnings in API Scanner.

- gradle.properties
Prevent Gradle from auto-downloading any missing JDK toolchain. We should be providing them ourselves.
The Jenkins image contains both JDK8 and JDK11.
> CORE-855: Disable Gradle's auto-provisioning for JDKs.

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
Gradle 7.0 will forbid finalizing a property before the task has executed.
> CORE-855: Resolve Gradle deprecation warnings in JarFilter.

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
Back-ported from the 6.x branch.
> CORE-855: Resolve Gradle deprecation warnings in JarFilter. (#375)

- README.md
- changelog.md
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarExtension.groovy
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarSuspendableTest.groovy
- quasar-utils/src/test/resources/repositories.gradle
Update `quasar-utils` to use the OSGi-compatible Quasar 0.8.x artifacts. The tests only verify the Quasar `-javaagent:` parameter is correct, and do not actually instrument any classes. This means that they do not need to be executed on a Java 11+ JVM.
> CORE-855: Update quasar-utils plugin to use OSGi Quasar 0.8.x.

- cordformation/build.gradle
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- cordformation/src/main/kotlin/net/corda/plugins/CordformationUtils.kt
- cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- cordformation/src/test/resources/net/corda/plugins/DeployDockerImage.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithNetworkConfigWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExternalDBSettingsWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExtraCommandForDbSchema.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
- cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithNetworkConfigWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithDocker.gradle
- cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithExternalService.gradle
- cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithExternalServiceNoOption.gradle
- Replace uses of deprecated Gradle configurations.
- Update definition of `cordapp` configuration not to use deprecated `compile`.
- Use new `cordaRuntimeOnly` configuration instead of `cordaRuntime`.
- _Finally_ remove the deprecated `rpcPort` element from the DSL.
- Resolve compiler warnings.
> CORE-855: Update Cordformation plugin for Gradle 6.7.1.

- README.md
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- cordformation/src/main/kotlin/net/corda/plugins/CordformationUtils.kt
- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishConfigurationProjectListener.groovy
- publish-utils/src/main/groovy/net/corda/plugins/publish/PublishPlugin.groovy
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
A `cordaProvided` dependency contributes to `compileClasspath` but not to `runtimeClasspath`, because we expect Corda to provide it at runtime. However, we would also like to include it on the `testRuntimeClasspath`, `integrationTestRuntimeClasspath` etc to make developers' testing easier.
We will use the contents of the `runtimeClasspath` to determine the dependencies to include in the CPK, and so need to keep it free of Corda artifacts and their transitive dependencies.
Also update `publish-utils` for Gradle 6.6 lazy artifact support, c.f. "task configuration avoidance".
> CORE-855: Adjust definition of cordaProvided configuration.

- README.md
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
Ensure the legacy `cordapp` plugin does not try to fat-jar the new OSGi artifacts for Quasar or Kotlin. Also update some of its internals for newer Gradle APIs. However, the plugin itself must remain backwards compatible with its previous versions.
> CORE-855: Update legacy cordapp plugin for Gradle 6.7.1.

- api-scanner/src/main/java/net/corda/plugins/apiscanner/ApiScanner.java
- api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java
- cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterConfigurationTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterExecuteTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConfigurationTests.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixExecuteTest.kt
- jar-filter/src/test/resources/basic-execute/build.gradle
- jar-filter/src/test/resources/basic-execute/kotlin/net/corda/gradle/ExampleKotlin.kt
Preserve JarFilter's public API. However, the `ScanApi` task is private and can be streamlined.
> CORE-855: A better fix for deprecation warning in API Scanner and JarFilter. (#377)

- flask/src/main/java/net/corda/gradle/flask/FlaskJarTask.java
Ensure two parallel `flaskJar` tasks use separate temporary files.
> CORE-727: Generate a unique filename for flask temporary file.

- flask/src/main/java/net/corda/gradle/flask/FlaskJarTask.java
- flask/src/test/groovy/net/corda/gradle/flask/FlaskPluginTest.groovy
A directory entry contains zero bytes and should be `STORED`. It is also unsafe to add a `ZipEntry` from a `ZipInputStream` directly into a `ZipOutputStream` as a `ZipEntry` field has several internal fields that its stream will update.
Also create a temporary subdirectory for the heartbeat agent when adding it to the flask.
> CORE-727: Initialize new ZipEntry objects more thoroughly.

- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterTimestampTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixTimestampTest.kt
Allow these final two Gradle test projects to be debugged.
> NOTICK: Enable debugging for two JarFilter test projects.

- flask/build.gradle
- flask/src/main/java/net/corda/gradle/flask/FlaskJarTask.java
- flask/src/test/groovy/net/corda/gradle/flask/FlaskPluginTest.groovy
We create zip directory entries in two places, so move their creation into `ZipEntryFactory` and then add a test to ensure we have caught them all.
Move handling of the "last modified" timestamp into `ZipEntryFactory` too.
Note: When using `ZipInputStream`, each `ZipEntry`'s `time`, `comment` and `extra` values are available immediately. But a `DEFLATED` entry's entire `InputStream` needs to be consumed before its `size`, `compressedSize` and `crc` values are set.
(:rotating_light: And this commit can be _**SQUASHED**_ too! :rotating_light:)
> CORE-727: Create directory ZipEntry objects using the factory.

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/UnwantedCache.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteInnerLambdaTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixAnnotationTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorDefaultParameterTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseDeleteConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseStubConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/StubConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/KotlinMatchers.kt
- Stop filtering methods and fields once we decide to delete the class.
- Differentiate between matchers for Java and Kotlin constructors.
- Fix some whitespace issues.
> NOTICK: Clean some JarFilter technical debt.

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/UnwantedCache.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteInnerLambdaTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixAnnotationTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorDefaultParameterTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseDeleteConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseStubConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/StubConstructorTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/KotlinMatchers.kt
- Stop filtering methods and fields once we decide to delete the class.
- Differentiate between matchers for Java and Kotlin constructors.
- Fix some whitespace issues.
> NOTICK: Clean some JarFilter technical debt: (#391)

- flask/flask-common/src/main/java/net/corda/flask/common/LockFile.java
- flask/flask-launcher/src/main/java/net/corda/flask/launcher/Launcher.java
`RandomAccessFile` is a `Closeable` and needs to be closed, otherwise it will leak an open file descriptor that could prevent the file from being deleted on some OSes (namely Windows)
> CORE-924 fixed RandomAccessFile leak

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteAmbiguousPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteAndStubTests.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteClassReferencesTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteExtensionValPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteLazyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteValPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteVarPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/RemoveAnnotationsTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/JavaMatchers.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/KotlinMatchers.kt
- jar-filter/src/test/resources/delete-class-references/build.gradle
- jar-filter/src/test/resources/delete-class-references/kotlin/net/corda/gradle/UsesUnwantedData.kt
Methods with a deleted return type or parameter type must be deleted too. Similarly fields whose type has been deleted.
We also need to remove Kotlin metadata for properties without a backing field whose accessor functions have all been deleted.
> NOTICK: Delete methods and fields whose descriptors contain deleted types.

- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteAmbiguousPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteAndStubTests.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteClassReferencesTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteExtensionValPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteLazyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteValPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteVarPropertyTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/RemoveAnnotationsTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/JavaMatchers.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/KotlinMatchers.kt
- jar-filter/src/test/resources/delete-class-references/build.gradle
- jar-filter/src/test/resources/delete-class-references/kotlin/net/corda/gradle/UsesUnwantedData.kt
Methods with a deleted return type or parameter type must be deleted too. Similarly fields whose type has been deleted.
We also need to remove Kotlin metadata for properties without a backing field whose accessor functions have all been deleted.
> NOTICK: Delete methods and fields whose descriptors contain deleted types. (#393)

- flask/flask-heartbeat-agent/build.gradle
- flask/flask-launcher/src/main/java/net/corda/flask/launcher/JarCache.java
Every flask process extract its own jar dependencies in a shared cache; in the cache folder the path to each jar is `lib/${SHA256_OF_THE_JAR}/${JAR_FILE_BASENAME}.jar`; before starting the extraction the process checks that the path doesn't already exist to avoid harming other processes that may be already running and using that jar (rewriting the file with one with identical content could break java processes reading from that file). The problem is that the jar may already exist in the cache because another process created it, but that process might still be writing the jar to the disk.
The result is that a Java process starts with the assumption that all of its dependencies are already in place while they might actually be incomplete (because extracting a big jar to the disk takes some …
> Fixed race condition on jar extraction

- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/main/kotlin/net/corda/plugins/CordaMock.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordapp.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- cordformation/src/main/kotlin/net/corda/plugins/RpcSettings.kt
- cordformation/src/test/kotlin/net/corda/plugins/Assertions.kt
- cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordaMockTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/DockerformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/KotlinCordformTest.kt
- cordformation/src/test/resources/net/corda/plugins/CompatibilityKotlinDSL.gradle.kts
- cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordapp.gradle.kts
Replace `Closure` in `cordformation`'s DSL with modern `Action`. This makes `cordformation` compatible with Gradle's Kotlin DSL as well as with Groovy.
This should fix #403.
> CORE-1134: Replace cordformation DSL Closure elements with Action.

- cordformation/src/main/kotlin/net/corda/plugins/Node.kt
The `node.cordapps = []` elements was supposed to have been deleted from Cordformation already, but has somehow survived. But no longer! It will not trouble the Corda Gradle plugins' 6.x series.
> CORE-145: Remove long-deprecated DSL feature from Cordformation.

- changelog.md
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
The `Baseform.signing` field is not an `@Input` property, but its contents are. Annotate `signing` as `@Nested` to instruct Gradle to examine `signing` for task properties.
> NOTICK: Annotate Baseform.signing field as "Nested".

- cordapp/build.gradle
- cordformation/build.gradle
- publish-utils/build.gradle
Back-port Gradle changes for better "correctness". Also, we want to get rid of `jcenter()` anyway before this repository goes dark.
> NOTICK: Fix Gradle deprecations (to be removed in Gradle 8). (#410)

- flask/flask-common/src/main/java/net/corda/flask/common/Flask.java
- flask/flask-launcher/build.gradle
- flask/flask-launcher/src/main/java/net/corda/flask/launcher/JavaProcessBuilder.java
- flask/flask-launcher/src/main/java/net/corda/flask/launcher/Launcher.java
- flask/src/main/groovy/net/corda/gradle/flask/FlaskPlugin.groovy
- flask/src/main/java/net/corda/gradle/flask/FlaskJarTask.java
- flask/src/test/groovy/net/corda/gradle/flask/FlaskPluginTest.groovy
- flask/src/test/resources/testProject/build.gradle
- flask/src/test/resources/testProject/src/main/java/net/corda/gradle/flask/test/HangingMain.java
The current version of flask calls `Process.destroyForcibly` on the child process immediately after calling `Process.destroy` and without waiting for a graceful shutdown of the child process.
I've also added the `net.corda.flask.kill.timeout.millis` JVM property to set the timeout before forcibly killing the child process if it doesn't gracefully terminate.
> NOTICK Fix shutdown hook execution on flask jars

- flask/build.gradle
- flask/flask-heartbeat-agent/build.gradle
- flask/flask-launcher/build.gradle
Fix errors and warnings that are highlighted by Gradle 7.0. (Note that we are still using Gradle 6.7.1, but should be upgrading to Gradle 6.8.3 soon.)
> NOTICK: Fix Gradle deprecations that will become errors later.

- README.md
- api-scanner/src/test/java/net/corda/plugins/apiscanner/KotlinAnnotationsTest.java
- api-scanner/src/test/java/net/corda/plugins/apiscanner/KotlinConstantTest.java
- api-scanner/src/test/resources/gradle.properties
- api-scanner/src/test/resources/kotlin.gradle
- build.gradle
- cordapp/src/test/resources/gradle.properties
- cordformation/src/test/resources/gradle.properties
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- jar-filter/build.gradle
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/KotlinAwareVisitor.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/SanitisingTransformer.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DummyJar.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterProject.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterTimestampTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixAnnotationTest.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixProject.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixTimestampTest.kt
- jar-filter/src/test/resources/gradle.properties
- jar-filter/src/test/resources/kotlin.gradle
- jar-filter/unwanteds/build.gradle
- quasar-utils/src/test/resources/gradle.properties
- settings.gradle
Plugins written in Kotlin are still compiled to use the Kotlin 1.3 API, despite Gradle 6.8.3 using the Kotlin 1.4 runtime libraries. This should allow Gradle versions < 6.8 to continue using them.
JarFilter uses the `kotlinx-metadata-jvm` library, the latest version of which now _requires_ Kotlin 1.4. So JarFilter 6 now requires Gradle 6.8+. (This shouldn't be an issue for Corda.)
Also upgrade the following:
- JUnit 5.7.0 -> 5.7.1
- Artifactory plugin 4.20.0 -> 4.21.0
- Gradle Publish plugin 0.12.0 -> 0.14.0
- Gradle Enterprise Plugin 3.6 -> 3.6.1
> CORE-1161: Upgrade to Gradle 6.8.3.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CPKDependenciesTask.kt
- jar-filter/build.gradle
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DummyJar.kt
- Resolve some compiler warnings.
- Improve KDocs slightly.
- JarFilter project now uses JaCoCo 0.8.7.
> NOTICK: Clear some trivial technical debt.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CPKDependenciesTask.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyConstraintsTask.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/PackagingTask.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappTransitiveDependencyTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/GradleProject.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/SimpleCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/SimpleKotlinCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/TransitiveCordappsTest.kt
Modify the `cordapp-cpk` plugin's `PackagingTask` to extract the `CPKDependencies` file from the "main" jar and include it inside the `.cpk` file too.
> CORE-1300: Copy CPKDependencies into the CPK file.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/PackagingTask.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappTransitiveDependencyTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/SimpleCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/SimpleKotlinCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/TransitiveCordappsTest.kt
Remove the duplicate `CPKDependencies` from the `.cpk` file. We do not want this "convenient" duplicate to become the de-facto "master" copy.
Keep the extra tests though :grinning:.
> CORE-1300: Revert duplication of CPKDependencies into CPK.

- build.gradle
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappGradleConfigurationsTest.kt
- gradle/wrapper/gradle-wrapper.properties
This release backports important fixes from Gradle 7.0.
> NOTICK: Upgrade to Gradle 6.9.

- cordapp-cpk/build.gradle
- cordapp-cpk/src/main/java/net/corda/plugins/cpk/XMLFactory.java
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CPKDependenciesTask.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyCalculator.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyConstraintsTask.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/PackagingTask.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/SignJar.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/VerifyBundle.kt
- cordapp-cpk/src/test/java/net/corda/plugins/cpk/xml/XMLFactory.java
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/GradleProject.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/xml/XmlSchema.kt
- cordapp-cpk/src/test/resources/xml/corda-cpk-1.0.xsd
- Create a schema XSD describing the CorDapp `CPKDependencies` and `DependencyConstraints` XML documents, and update tests to validate them both against it.
- Prefix XML namespace with `urn:` to make a valid URI (as required).
- Apply "best practices" for JAXP.
- Rewrite JAXP factories in Java to work around a problem with the Kotlin compiler.
> CORE-1335: Validate the CPK XML against a schema XSD.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyCalculator.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/PackagingTask.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappApiLibraryTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/GradleProject.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/SimpleCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/SimpleKotlinCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithCordaMetadataTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithDependentCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithProvidedLibraryTest.kt
- cordapp-cpk/src/test/resources/corda-api/build.gradle
- cordapp-cpk/src/test/resources/cordapp-api-library/build.gradle
- cordapp-cpk/src/test/resources/cordapp-api-library/cordapp/build.gradle
- cordapp-cpk/src/test/resources/cordapp-api-library/settings.gradle
- cordapp-cpk/src/test/resources/cordapp-api-library/src/main/kotlin/com/example/workflow/ExampleWorkflow.kt
- cordapp-cpk/src/test/resources/with-dependent-cordapp/build.gradle
- cordapp-cpk/src/test/resources/with-dependent-cordapp/library/build.gradle
- cordapp-cpk/src/test/resources/with-provided-library/build.gradle
- cordapp-cpk/src/test/resources/with-provided-library/library/build.gradle
- cordapp-cpk/src/test/resources/with-provided-library/settings.gradle
- Compute `Cordapp-Built-Platform-Version` manifest tag for each "main" jar.
- Copy `Cordapp-Built-Platform-Version` into CPK manifest as `Corda-CPK-Built-Platform-Version`.
- Remove any transitive dependencies belonging to dependent CPKs from our compile classpath. This
allows us to simplify how we create the Gradle configurations.
Also extend the test coverage to examine the compile classpaths when building CorDapps.
> CORE-1390: Compute the highest platform version used by the CorDapp.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarExtension.groovy
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy
- Log a warning if the `quasar-utils` plugin has not been configured with an explicit `@Suspendable` annotation - either via the `quasar_suspendable_annotation` property or via the `quasar` DSL extension. This warning will only be displayed once per project.
- Ensure that the `cordaProvided` and `cordaRuntimeOnly` configurations defined by `quasar-utils` exactly match the same configurations created by the `cordapp-cpk` plugin. The point is that it shouldn't matter which plugin creates these configurations in practice.
> CORE-1434: Warn if `@Suspendable` not configured for quasar-utils.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/VerifyBundle.kt
Bnd generates the validation error messages, but we can add some general advice afterwards about the probable cause of the underlying problems.
> CORE-268: Improve message for CPK validation errors.

- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
Use the latest version of Quasar by default.
> CORDA-4157: Upgrade quasar-utils to use Quasar 0.8.6_r3.

- cordapp-cpk/build.gradle
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/AttributeFactory.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyCalculator.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/VerifyBundle.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappWithEmbeddedTransitivesTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappWithLoggingTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/GradleProject.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithDependentCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithEmbeddedJarTest.kt
- cordapp-cpk/src/test/resources/corda-api/build.gradle
- cordapp-cpk/src/test/resources/cordapp-with-logging/build.gradle
- cordapp-cpk/src/test/resources/cordapp-with-logging/settings.gradle
- cordapp-cpk/src/test/resources/cordapp-with-logging/src/main/java/com/example/contract/LoggingContract.java
- cordapp-cpk/src/test/resources/gradle.properties
- cordapp-cpk/src/test/resources/with-dependent-cordapp/build.gradle
- cordapp-cpk/src/test/resources/with-dependent-cordapp/cordapp/build.gradle
Add an extra validation step to the CPK `verifyBundle` task to check that the package imports align with the package exports. Also resolve the (`cordapp`, `cordaProvided`) configurations separately from `compileClasspath` for this, so that their transitive dependencies are not affected by the contents of the CPK. (We need this to make the `verifyBundle` task meaningful.)
> CORE-1589: Verify CPK OSGi imports match classpath exports.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CPKDependenciesTask.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappDependencyCollector.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithoutTransitiveCordappsTest.kt
- cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/services/lifecycle/package-info.java
- cordapp-cpk/src/test/resources/cordapp-private-deps/build.gradle
- cordapp-cpk/src/test/resources/cordapp-private-deps/cordapp/build.gradle
- cordapp-cpk/src/test/resources/transitive-cordapps/cpk-two/build.gradle
- cordapp-cpk/src/test/resources/without-transitive-cordapps/build.gradle
- cordapp-cpk/src/test/resources/without-transitive-cordapps/cpk-one/build.gradle
- cordapp-cpk/src/test/resources/without-transitive-cordapps/cpk-two/build.gradle
- cordapp-cpk/src/test/resources/without-transitive-cordapps/settings.gradle
- cordapp-cpk/src/test/resources/xml/corda-cpk-1.0.xsd
CorDapp dependencies that are declared as not being transitive should not be picked up by the `CordappDependenyCollector`, which means that they will not be implicitly added to the CPK. Nor will their `cordaProvided` dependencies be implicitly included in the `cordaAllProvided` configuration.
> CORE-268: Honour dependency transitivity for cordapp and cordaProvided.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/OsgiExtension.kt
- cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/services/persistence/package-info.java
- cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/persistence/package-info.java
- cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/persistence/MappedSchema.kt
- cordapp-cpk/src/test/resources/with-corda-metadata/contracts/src/main/kotlin/com/example/metadata/schemas/ExampleSchema.kt
Update the dummy Corda API for new location of `MappedSchema` class.
> CORE-268: Update cordapp-cpk for new location of MappedSchema class.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyCalculator.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappJarForCPKDependenciesTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/GradleProject.kt
- cordapp-cpk/src/test/resources/cordapp-transitive-deps/build.gradle
Gradle's dependency graph for the `cordaCPKDependencies` task needs to include the `jar` tasks for any transitive CorDapp  projects. Replace the build dependencies from the `runtimeClasspath` and `compileClasspath` configurations with the `cordapp-cpk` plugin's `cordappPackaging` and `cordappExternal` configurations respectively, which are their "OSGi-aware" replacements.
This has also exposed a more subtle problem where Gradle sometimes resolves dependent CorDapp projects to their `build/classes/*/main` directories instead of their "main" jars. This is _**toxic**_ to OSGi because it deprives Bnd of those CorDapps' OSGi metadata, which in turn means that Bnd generates broken OSGi metadata for the new "main" jar. I have _hopefully_ resolved this by setting the `LibraryElements` variant …
> CORE-1921: Ensure we build the jars required by CPKDependencies XML.

- changelog.md
- settings.gradle
Remove these plugins from the build:
- `cordformation`: This is no longer compatible with Corda 5.
- `publish-utils`: Obsolete, now that Bintray is no longer operating.
> CORE-1931: Remove cordformation and publish-utils from build.

- cordapp-cpk/build.gradle
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/AttributeFactory.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/Attributor.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappDependencyCollector.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappClassesDependencyTest.kt
- cordapp-cpk/src/test/resources/cordapp-classes-dep/build.gradle
- cordapp-cpk/src/test/resources/cordapp-classes-dep/library/build.gradle
- cordapp-cpk/src/test/resources/cordapp-classes-dep/library/src/main/java/com/example/library/ExternalLibrary.java
- cordapp-cpk/src/test/resources/cordapp-classes-dep/library/src/main/java/com/example/library/impl/ExternalLibraryImpl.java
- cordapp-cpk/src/test/resources/cordapp-classes-dep/library/src/main/java/com/example/library/package-info.java
- cordapp-cpk/src/test/resources/cordapp-classes-dep/settings.gradle
- cordapp-cpk/src/test/resources/cordapp-classes-dep/src/main/kotlin/com/example/host/CordappHostContract.kt
- cordapp-cpk/src/test/resources/gradle.properties
Bnd _must_ compile against jars, and not against directories of classes. Set the `LibraryElements.JAR` variant attribute on the correct resolvable configurations to ensure that Gradle does this.
Bnd sets Gradle's `LibraryElements.JAR` attribute on the `compileClasspath` configuration for us already, but there's no harm in us setting it too. We also need to set this attribute on the `cordappExternal` configuration in order to be consistent with `compileClasspath`, and to configure any "detached configuration" used when tracing transitive CorDapp dependencies.
> CORE-1998: Ensure that cordapp-cpk plugin always compiles against jars.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/PublishAfterEvaluationHandler.kt
- cordapp-cpk/src/test/resources/transitive-cordapps/build.gradle
The most reliable way to check whether a project has a CPK to publish is to use the plugin manager.
> CORE-2057: Update how the CPK tests publish CPKs.

- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/GradleProject.kt
It is reasonable to expect `GradleProject.withSubResource()` not to install the sub-resources until the Gradle project executes "build", which allows the builder's `withXXX()` methods to be invoked in any order.
> NOTICK: Implement GradleProject.withSubResource correctly for "builder" pattern.

- cordapp-cpk/src/test/resources/cordapp-cpb/build.gradle
- cordapp-cpk/src/test/resources/external-cordapp/build.gradle
- cordapp-cpk/src/test/resources/external-cordapp/corda-platform-cordapp/build.gradle
- cordapp-cpk/src/test/resources/external-cordapp/external-cordapp-transitive-dependency/build.gradle
Update Groovy and Gradle for Gradle 6+ best practices.
Also remove some unnecessary `minimumPlatformVersion` properties.
> NOTICK: Update Groovy and Gradle constructs.

- build.gradle
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyCalculator.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/OsgiExtension.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/ConfigureCordaMetadataTest.kt
- cordapp-cpk/src/test/resources/configure-corda-metadata/build.gradle
- cordapp-cpk/src/test/resources/configure-corda-metadata/cordapp/build.gradle
- cordapp-cpk/src/test/resources/cordapp-configuration/src/main/resources/net/corda/cordapp/cordapp-configuration.properties
- cordapp-cpk/src/test/resources/with-corda-metadata/build.gradle
Corda's APIs currently all live under this package mask:
```
net.corda.v5.*
```
We expect to add other masks over time. Add a new `Import-Policy-Packages` property to `cordapp-configuration.properties` containing these package masks as a comma-separated list. The `cordapp-cpk` plugin will uses these masks to create extra `Import-Package` instructions for Bnd:
```
net.corda.v5.*;version='${range;[=,+);${@}}'
```
The `${range}` macro here will ensure that OSGi will only check the Corda API major version number when loading CorDapps, e.g.:
```
5 <= version < 6
```
> CORE-2087: Allow cordapp-cpk to apply OSGi "consumer policy" to Corda packages.

- gradle.properties
The `biz.aQute.bnd.annotation:5.3.0` artifact actually depends on OSGi 8.0.0, so upgrade our test dependency to match.
> NOTICK: Test using OSGi 8.0.0, which is what Bnd 5.3 supports.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpb/CpbPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
When CorDapp developers set `archiveBaseName` and/or `archiveAppendix` for the `jar` task, also use these values as the defaults for both `cpk` and `cpb` tasks.
This doesn't prevent developers from _explicitly_ setting these values for `cpk` and `cpb` tasks. It only guarantees that they will both match the `jar` task unless explicitly set differently.
> CORE-2336: Use jar task as convention for CPK and CPB tasks.

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
[Gradle 6.9.1 has been released.](https://docs.gradle.org/6.9.1/release-notes.html)
This contains fixes back-ported from Gradle 7.
> NOTICK: Upgrade to Gradle 6.9.1.

- build.gradle
- cordapp-cpk/build.gradle
- jar-filter/build.gradle
Use Dokka for Kotlin plugins, and Gradle's own `publishPluginJavaDocsJar` docs task otherwise. This prevents us generating duplicate `index.html` files, which will break the build in Gradle 7.x.
> NOTICK: Either generate KDocs or Javadocs, but not both.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/PublishAfterEvaluationHandler.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/TransitiveRemoteCordappsTest.kt
- cordapp-cpk/src/test/resources/transitive-cordapps/build.gradle
Maven Central requires POMs to contain the following extra fields:
- `name`
- `scm`
- `licenses`
- `developers`
And include `organization` too, for good measure.
> CORE-2495: Copy name, scm, licenses and developers to CPK companion POM.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyCalculator.kt
CPKs do not need to contain `org.jetbrains:annotations`. This is just a transitive dependency of
```groovy
'net.corda.kotlin:kotlin-stdlib-jdk8-osgi'
```
that is not required by
```groovy
'org.jetbrains.kotlin:kotlin-osgi-bundle'
```
> CORE-2578: Exclude JetBrains' annotations jar from CPKs.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/OsgiExtension.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/Assertions.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappWithSchemaTest.kt
- cordapp-cpk/src/test/resources/cordapp-with-schema/build.gradle
- cordapp-cpk/src/test/resources/cordapp-with-schema/settings.gradle
- cordapp-cpk/src/test/resources/cordapp-with-schema/src/main/kotlin/com/example/schema/SchemaContract.kt
- cordapp-cpk/src/test/resources/cordapp-with-schema/src/main/resources/migration/sample-migration-v1.0.xml
- cordapp-cpk/src/test/resources/cordapp-with-schema/src/main/resources/migration/sample.changelog-master.xml
We expect Liquibase migration scripts to be added to a CPK "main" jar's `migration` package. However, we also cannot allow two CPKs to export the same package into the OSGi framework. Together, these two constraints _require_ that `migration.*` is always `Private-Package`, regardless of the `jar` task's
```gradle
osgi {
autoExport = true
}
```
setting.
> CORE-2591: CPK 'migration' package should be private by default.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/OsgiExtension.kt
- cordapp-cpk/src/test/resources/corda-api/build.gradle
- gradle.properties
Bnd 6.0.0 has been released with [these changes](https://github.com/bndtools/bnd/wiki/Changes-in-6.0.0).
We can now make our import policy instruction "optional", so that it won't generate warnings if no packages need to apply it.
Bnd 6.0.0 also replaces deprecated Gradle `Convention` objects with `Extension` objects, so the `cordapp-cpk` plugin has been updated accordingly.
> CORE-2739: Upgrade to Bnd 6.0.0.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- gradle.properties
Upgrade Bnd 6.0.0 -> 6.1.0.
Also prevent Bnd from accessing the Gradle project's properties when configuring the `jar` task.
> CORE-3127: Upgrade Bnd 6.0.0 -> 6.1.0.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CPKDependenciesTask.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyCalculator.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/VerifyBundle.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpb/CpbTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappApiLibraryTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappJarForCPKDependenciesTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappPrivateDependencyTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappTransitiveDependencyTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/GradleProject.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/HashSelectionTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/TransitiveCordappsTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/VerifyCordappDependencyTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithDependentCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithoutTransitiveCordappsTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/xml/XmlSchema.kt
- cordapp-cpk/src/test/resources/hash-selection/build.gradle
- cordapp-cpk/src/test/resources/hash-selection/cordapp/build.gradle
- cordapp-cpk/src/test/resources/hash-selection/cordapp/settings.gradle
- cordapp-cpk/src/test/resources/hash-selection/settings.gradle
- cordapp-cpk/src/test/resources/xml/corda-cpk-1.0.xsd
Denote dependent CPKs which belong to the same Gradle build as the CPK that the `cordapp-cpk` plugin is building as all being signed with the same key. This allows us to avoid writing the SHA-256 of the "development" key into the CPK's `META-INF/CPKDependencies` file, and hence to sign all of these CPKs later with the actual "release" key.
CPKs which are downloaded from a Maven repository are assumed to have been signed with their correct "release" key.
> CORE-3049: Differentiate between remote and project CPK dependencies.

- flask/build.gradle
- flask/flask-common/build.gradle
- flask/flask-common/src/main/java/net/corda/flask/common/Flask.java
- flask/flask-common/src/main/java/net/corda/flask/common/LockFile.java
- flask/flask-common/src/main/java/net/corda/flask/common/ThrowingConsumer.java
- flask/flask-common/src/main/java/net/corda/flask/common/ThrowingFunction.java
- flask/flask-common/src/main/java/net/corda/flask/common/ThrowingSupplier.java
- flask/flask-heartbeat-agent/src/main/java/net/corda/flask/HeartbeatAgent.java
- flask/flask-launcher/build.gradle
- flask/flask-launcher/src/lockFileTest/java/net/corda/flask/launcher/LockFileTestMain.java
- flask/flask-launcher/src/main/java/net/corda/flask/launcher/JarCache.java
- flask/flask-launcher/src/main/java/net/corda/flask/launcher/JavaProcessBuilder.java
- flask/flask-launcher/src/main/java/net/corda/flask/launcher/Launcher.java
- flask/flask-launcher/src/test/java/net/corda/flask/launcher/LockFileTest.java
- flask/src/main/java/net/corda/gradle/flask/FlaskJarTask.java
- flask/src/main/java/net/corda/gradle/flask/HeartbeatAgentResource.java
- flask/src/main/java/net/corda/gradle/flask/LauncherResource.java
- flask/src/test/groovy/net/corda/gradle/flask/FlaskPluginTest.groovy
- flask/src/test/resources/testProject/src/flask/java/net/corda/gradle/flask/test/TestLauncher.java
- flask/src/test/resources/testProject/src/main/java/net/corda/gradle/flask/test/HangingMain.java
- gradle.properties
Remove Lombok from the `flask` plugin project so that there is less to maintain.
There should be no functional change, although we need some new functional interfaces that allow lambdas to throw exceptions.
> CORE-3384: Remove Lombok from the flask plugin.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpb/CpbPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
Resolve the `cpbPackaging` configuration via a `projectsEvaluated` handler instead of the project's own `afterEvaluate` handler. We _must not_ resolve this configuration until every other project in the build has also had a chance to apply the `cordapp-cpk` plugin.
This is a subtle fix to an incomplete workaround to a Gradle bug.
> CORE-3809: Fix cordapp-cpb plugin only to resolve cpbPackaging configuration after entire configuration phase.

- .ci/Jenkinsfile
- gradle/wrapper/gradle-wrapper.properties
Only Jenkins will now download Gradle from Artifactory.
> NOTICK: Switch Jenkins pipeline to using authenticated Gradle wrapper.

- jar-filter/build.gradle
- jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/KotlinAwareVisitor.kt
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/MetadataTools.kt
Upgrade Kotlin JVM Metadata library 0.2.0 -> 0.3.0.
This is the most up-to-date version that is still compatible with Kotlin 1.4.
> NOTICK: Upgrade Kotlin JVM Metadata library to 0.3.0.

- changelog.md
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
Update `quasar-utils` plugin to use Quasar 0.7.15_r3 by default.
> CORDA-4254: Upgrade default Quasar version to 0.7.15_r3.

- README.md
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpb/CpbPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/PublishAfterEvaluationHandler.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappWithPlatformTest.kt
- cordapp-cpk/src/test/resources/corda-api/build.gradle
- cordapp-cpk/src/test/resources/corda-platform/build.gradle
- cordapp-cpk/src/test/resources/external-cordapp/build.gradle
- cordapp-cpk/src/test/resources/hash-selection/cordapp/build.gradle
- cordapp-cpk/src/test/resources/publish-platform/build.gradle
- cordapp-cpk/src/test/resources/transitive-cordapps/build.gradle
- cordapp-cpk/src/test/resources/without-transitive-cordapps/build.gradle
Create a new `SoftwareComponent` called "cordapp" for publishing the CPK artifacts. This simplifies how to declare the contents of the `MavenPublication`, i.e.
```groovy
publishing {
publications {
maven(MavenPublication) {
from components.cordapp
}
}
}
```
> CORE-4748: Create cordapp component for publishing CPKs.

- cordapp-cpk/README.md
- cordapp-cpk/build.gradle
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappExtension.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/resources/net/corda/plugins/cpk/cordapp-cpk.properties
- gradle.properties
Add `osgi.annotation` as an explicit `compileOnly` dependency rather than relying on Bnd to introduce it as a transitive dependency of `biz.aQute.bnd.annotation`. Also update the `cordapp` extension so that we can choose the version of `osgi.annotation` to use.  (Defaults to `8.1.0`, to match the transitive dependency of `biz.aQute.bnd.annotation:6.2.0`.)
> CORE-4781: Update cordapp-cpk to add explicit compileOnly dependency for osgi.annotation.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarExtension.groovy
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
The `quasar-utils` plugin will now always create the `cordaProvided` and `cordaRuntimeOnly` configurations, and will adjust their definitions appropriately if/when the `java` plugin is also applied. This brings the plugin's behaviour more into line with its 5.1.0-SNAPSHOT version.
Also simplify how the `cordapp-cpk` plugin creates its `cordaRuntimeOnly` configuration, so that the code is more obviously the same, and ensure that Quasar's "exclusions" parameters are all genuine `String` objects.
> NOTICK: Refactor how we create Corda's configurations, hopefully for clarity.

- cordformation/build.gradle
- gradle.properties
Perform the following upgrades:
- Gradle publish-plugin 0.16.0 -> 0.21.0
- commons-compress -> 1.21
- JUnit 5.8.1 -> 5.8.2
- AssertJ 3.16.1 -> 3.22.0
> NOTICK: Upgrade Gradle publish plugin and commons-compress.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/VerifyLibraries.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/CordappWithNonBundleLibraryTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/GradleProject.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/SimpleCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/SimpleKotlinCordappTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/TransitiveRemoteCordappsTest.kt
- cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithDependentCordappTest.kt
- cordapp-cpk/src/test/resources/cordapp-api-library/cordapp/build.gradle
- cordapp-cpk/src/test/resources/cordapp-non-bundle-library/build.gradle
- cordapp-cpk/src/test/resources/cordapp-non-bundle-library/settings.gradle
- cordapp-cpk/src/test/resources/simple-kotlin-cordapp/build.gradle
- cordapp-cpk/src/test/resources/with-dependent-cordapp/build.gradle
- cordapp-cpk/src/test/resources/with-dependent-cordapp/library/build.gradle
Prevent CPKs from including library jars which are not OSGi bundles. The CPK cannot possibly use these jars since their lack of OSGi metadata would prevent the `verifyBundle` task from resolving their contents. Most likely, they are simply transitive "junk" dependencies.
> CORE-5068: Verify that every CPK library is also a bundle.

- cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
We can get the `SourceSetContainer` directly, without using the `JavaPluginExtension`.
> NOTICK: Fetch SourceSetContainer extension directly.

- cordapp-cpk2/build.gradle
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/CordappWithEmbeddedTransitivesTest.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/CordappWithPlatformTest.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/GradleProject.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/SimpleKotlinCordappTest.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/TransitiveCordappsTest.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/TransitiveRemoteCordappsTest.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/VerifyCordappDependencyTest.kt
- cordapp-cpk2/src/test/resources/gradle.properties
- cordapp-cpk2/src/test/resources/kotlin.gradle
- jar-filter/build.gradle
- jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/Utilities.kt
- jar-filter/src/test/resources/gradle.properties
Set the `org.gradle.java.home` property for Gradle's test toolkit via the `GradleRunner` instead of `gradle.properties`, because we need to use the toolchain from the `Test` task.
Also upgrade the tests to use Kotlin 1.7.10.
> NOTICK: Set Test org.gradle.java.home based on correct Java toolchain.

- .ci/Jenkinsfile
changeRequest() seems to not be triggering correctly in all use cases -  use CHANGE_ID instead as this is only set by Jenkins in PR builds it simply will not exist otherwise
> NOTICK: Use env.CHANGE_ID rather than changeRequest() to ID if we are in a PR build

- .ci/nightly/JenkinsfileSnykScan
Adding in .ci/nightly/JenkinsfileSnykScan so project will be picked up on the following multibranch pipeline https://ci02.dev.r3.com/job/Corda5/view/%20C5-Snyk-Scans/job/Snyk-Scans/job/corda-gradle-plugins-snyk-scan/ 
To enable Synk scanning on release/5.1 for corda-gradle-plugins
> CORE-5071: Add snyk Gradle plugin to C5 projects

- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/DependencyCalculator.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/CordappGradleConfigurationsTest.kt
Restore the library log message and the tests covering the log messages.
> CORE-4355: Restore "CorDapp library dependency" log output

- .ci/Jenkinsfile
use just single space around `::` in Artifactory build name
> INFRA-1822: remove obsolete spaces

- changelog.md
- cordformation/build.gradle
- cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
- cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/DockerImageTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/DockerformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/KotlinCordformTest.kt
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
The `cordaCordapp` configuration is intended to be "consumed" rather than "resolved". Therefore create `BaseForm`'s task dependency using the configuration's `artifacts` instead of its `buildDependencies`.
And even better, I've worked out how to include our `net.corda.plugins.cordapp` plugin in a `net.corda.plugins.cordformation` test.
> CORDA-4262: Fix task dependency for cordformation's project CorDapp.

- cordformation/build.gradle
- cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/DockerImageTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/DockerformTest.kt
- cordformation/src/test/kotlin/net/corda/plugins/KotlinCordformTest.kt
- cordformation/src/test/resources/net/corda/plugins/CompatibilityKotlinDSL.gradle.kts
- cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
- cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordapp.gradle.kts
Cordformation tests that deploy locally-built CorDapps should apply our actual `net.corda.plugins.cordapp` plugin. Back-port this functionality from CORDA-4262 on the `release/5.1` branch.
> NOTICK: Backport cordformation test fixes from 5.1.x branch.

- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarExtension.groovy
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarSuspendableTest.groovy
The OSGi-aware Quasar agent has been replaced by an OSGi framework extension, and will soon cease to exist. Update `quasar-utils` to use the original Quasar agent instead,
> CORE-6321: Revert quasar-utils to using original Quasar agent.

- README.md
- changelog.md
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
Replace mentions of `quasar-core-osgi` with `quasar-core`, and remove other OSGi-related references.
> CORE-6321: Update changelog and README for quasar-utils.

- changelog.md
- settings.gradle
- whitelist.txt
Corda 5 no longer needs the flask plugin.
> NOTICK: Retire the flask plugin for 7.0.0.

- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CordappPlugin.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CordappUtils.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/OsgiExtension.kt
Log a warning should users try to build CorDapps without also applying Corda's `net.corda.cordapp.cordapp-configuration` plugin.
> NOTICK: Warn users to apply the cordapp-configuration plugin.

- cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
Allow `cordformation` to deploy Corda jars that have been published with archive appendix of `jdk11`.
> CORDA-4263: Allow cordformation to recognise jars with -jdk11 appendix.

- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/OsgiExtension.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/ConfigureCordaMetadataTest.kt
- cordapp-cpk2/src/test/resources/cordapp-configuration/src/main/resources/net/corda/cordapp/cordapp-configuration.properties
We may not wish for CPKs to import _every_ package with version mask "[==,+)". Allow us more flexibility to configure this per package via the Corda APIs' `cordapp-configuration` Gradle plugin.
Note that this only modifies the plugin's capabilities, not its current behaviour.
> CORE-6551: Allow us to adjust the "version mask" when importing packages into CPKs.

- README.md
- changelog.md
- quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarNoInstrumentTest.groovy
- quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy
Update `quasar-utils` plugin to use Quasar 0.8.8_r3 by default.
Also update documentation and tests.
> CORE-6789: Upgrade default Quasar version to 0.8.8_r3.

- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CordappPlugin.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/OsgiExtension.kt
Prevent CPK developers from accidentally clobbering our Bnd instructions - as much as possible, anyway.
> NOTICK: Protect Bnd instructions from being clobbered accidentally.

- jar-filter/unwanteds/build.gradle
The `:jar-filter:unwanteds` is a test artifact that is built using Kotlin. Snyk really has no business scanning it in the first place, but converting its Kotlin dependency from `api` to `compileOnly` should suffice for now since Snyk should only be scanning the `runtimeClasspath` configurations.
> CORE-6614: Remove Kotlin from :jar-filter:unwanteds runtimeClasspath.

- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/OsgiExtension.kt
Add the `applyImportPolicies` property to the jar task's inputs when creating CPKs. This is largely for "completeness" because the policies are included into the `Import-Package` instruction anyway. However, it does allow Gradle to rebuild CPKs if this flag changes, which is what developers would expect to happen even if it makes no difference to Gradle.
> CORE-6551: Add applyImportPolicies to CPK plugin's task inputs.

- .ci/Jenkinsfile
Description:
Removing --all-sub-projects arg from SNYK_COMMANDS as recently we updated snykDeltaScan to use the --file arg and both being added causes multiple vulnerability reports to be generated by snyk test which means when the result is piped to snyk delta the execution fails.
Tested Against:
https://ci01.dev.r3.com/job/Corda-Gradle-Build-Plugins/job/corda-gradle-plugins/job/PR-561/5/
> NOTICK: Removing --all-sub-projects arg from SNYK_COMMANDS

- gradle.properties
the following transitive dependency from older versions of this plugin is no longer available,   `org.jfrog.buildinfo:build-info-extractor:2.23.0`
Bumping to latest plugin version resolves this  as this is no longer on dependency graph
> NOTICK: Bump version due to issue with transitive dependencies no longer being available 

- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CordappPlugin.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/SimpleCordappTest.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/SimpleKotlinCordappTest.kt
The `Created-By` and `Tool` manifest attributes break the reproducibility of CPK builds across different JDKs or versions of Bnd. Instruct Bnd not to include them into the CPKs.
> CORE-8937: Instruct Bnd not to add any extra headers into the CPK manifest.

- changelog.md
- cordapp-cpk2/build.gradle
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpb2/CpbPlugin.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CPKDependenciesTask.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CordappData.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CordappExtension.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CordappPlugin.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/DependencyCalculator.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/OsgiExtension.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/PublishAfterEvaluationHandler.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/SignJar.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/Signing.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/VerifyBundle.kt
- cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/VerifyLibraries.kt
- cordapp-cpk2/src/main/resources/net/corda/plugins/cpk2/cordapp-cpk2.properties
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/CordappGradleConfigurationsTest.kt
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/WithDependentCordappTest.kt
- cordapp-cpk2/src/test/resources/cordapp-embedded-overrides/src/main/java/com/example/embeddedoverrides/ExampleContract.java
- cordapp-cpk2/src/test/resources/cordapp-import-package/src/main/java/com/example/importpackage/ExampleContract.java
- cordapp-cpk2/src/test/resources/cordapp-override-version/src/main/java/com/example/overrideversion/ExampleContract.java
- cordapp-cpk2/src/test/resources/cordapp-scan-overrides/src/main/java/com/example/scanoverrides/ExampleContract.java
- cordapp-cpk2/src/test/resources/cordapp-with-guava/src/main/java/com/example/contract/GuavaContract.java
- cordapp-cpk2/src/test/resources/cordapp-with-logging/src/main/java/com/example/contract/LoggingContract.java
- cordapp-cpk2/src/test/resources/cpb-disable-jar/src/main/java/com/example/cpb/nojar/ExampleContract.java
- cordapp-cpk2/src/test/resources/cpk-disable-jar/src/main/java/com/example/nojar/ExampleContract.java
- cordapp-cpk2/src/test/resources/cpk-export-reserved-package/src/main/java/net/corda/contract/ExampleContract.java
- cordapp-cpk2/src/test/resources/cpk-export-reserved-package/src/main/java/net/corda/test/ExampleContract.java
- cordapp-cpk2/src/test/resources/gradle.properties
- cordapp-cpk2/src/test/resources/simple-cordapp/src/main/java/com/example/contract/ExampleContract.java
- gradle.properties
Allow CPK developers access to the JetBrain annotations at compile time, exactly as if they were using `kotlin-stdlib` instead of `kotlin-osgi-bundle`.
> CORE-10230: Automatically include JetBrains annotations as compile-only dependency.

- changelog.md
- cordapp-cpk2/src/main/java/net/corda/plugins/cpk2/CordappDependencyCollector.java
- cordapp-cpk2/src/main/java/net/corda/plugins/cpk2/CordappPlugin.java
- cordapp-cpk2/src/main/java/net/corda/plugins/cpk2/PomXmlWriter.java
- cordapp-cpk2/src/main/java/net/corda/plugins/cpk2/PublishAfterEvaluationHandler.java
The `MavenPom.getName()` is a Gradle property, so map the parent name instead of assigning it.
Rename this POM as a "marker" rather than a "companion".
> NOTICK: Fix generated name for CPK marker POM.

- cordapp-cpk2/README.md
Document the `osgi.symbolicName` property so that people don't mistakenly believe that they need to preserve a CorDapp's `project.group`, `archiveBaseName`, `archiveAppendix` and `archiveClassifier` values.
> DOC-5285: Document the cordapp-cpk2 plugin's symbolicName property.

- changelog.md
- cordapp-cpk2/build.gradle
- cordapp-cpk2/src/main/resources/net/corda/plugins/cpk2/cordapp-cpk2.properties
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpk2/WithDependentCordappTest.kt
- cordapp-cpk2/src/test/resources/gradle.properties
- cordapp-cpk2/src/test/resources/with-dependent-cordapp/build.gradle
- gradle.properties
Bndlib 6.4.1 has been released, although it has is no accompanying Gradle plugin. Upgrade `cordapp-cpk2` to use Bndlib 6.4.1 while still using Bnd's 6.4.0 builder plugin.
> CORE-14504: Upgrade to Bndlib 6.4.1.

- .ci/Jenkinsfile
- build.gradle
- cordapp-cpk2/src/test/resources/gradle.properties
- cordapp-cpk2/src/test/resources/repositories.gradle
- cordformation/src/test/resources/gradle.properties
- cordformation/src/test/resources/repositories.gradle
- quasar-utils/src/test/resources/gradle.properties
- quasar-utils/src/test/resources/repositories.gradle
Relates to [ES-486](https://r3-cev.atlassian.net/browse/ES-486) Remove public facing access to Artifactory
[ES-486]: https://r3-cev.atlassian.net/browse/ES-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Standard publishing to Artifactory remains as this is the ultimate source of truth. 
Separate automation is in place such if an item is removed from artifactory it is removed from S3.
also, this PR removes some redundant references in the Jenkins file to Nexus
> ES-858: Update Corda Gradle plugins post artifactory change

- changelog.md
- cordapp-cpk2/src/main/java/net/corda/plugins/cpb2/CpbPlugin.java
- cordapp-cpk2/src/main/java/net/corda/plugins/cpk2/CordappDependencyCollector.java
- cordapp-cpk2/src/main/java/net/corda/plugins/cpk2/CordappPlugin.java
- cordapp-cpk2/src/main/java/net/corda/plugins/cpk2/CordappUtils.java
Gradle 8+ requires each `Configuration`'s `canBeConsumed`, `canBeResolved` and `canBeDeclared` flags to be set consistently.
- `canBeConsumed`, `canBeResolved` must not both be true.
- `canBeConsumed`, `canBeDeclared` must not both be true.
`setCanBeDeclared()` was introduced in Gradle 8.2, so set this flag reflectively to preserve the plugin's compatibility with Gradle 7.
> CORE-17149: Set Configuration flags correctly for Gradle 8+.

- cordapp-cpk2/src/main/java/net/corda/plugins/cpb2/CpbPlugin.java
- cordapp-cpk2/src/main/java/net/corda/plugins/cpb2/CpbTask.java
- cordapp-cpk2/src/main/java/net/corda/plugins/cpk2/CordappUtils.java
- cordapp-cpk2/src/test/kotlin/net/corda/plugins/cpb2/CpbSharedName.kt
- cordapp-cpk2/src/test/resources/cpb-shared-name/build.gradle
- cordapp-cpk2/src/test/resources/cpb-shared-name/project-dependency/build.gradle
- cordapp-cpk2/src/test/resources/cpb-shared-name/second-project-dependency/build.gradle
- cordapp-cpk2/src/test/resources/cpb-shared-name/settings.gradle
As part of https://github.com/corda/corda-gradle-plugins/pull/595, we are adding the ability for users to set an identifiable name for their own CPKs. However, we do not want 2 CPKs in the same CPB to have the same name, so we need to add a check in the CPB plugin to ensure that names are not reused within it.
> CORE-17494: Add check to CPB creation to ensure that 2 CPKs don't share a name

- .ci/Jenkinsfile
This pipeline was previously broken as eks-e2e-01 wasn't available on ci01. this has now been added and can be reverted
> ES-2432/Use cordaPipelineKubernetesAgent
