README.md, changelog.md, constants.properties
=> Release 4.0.0

constants.properties, cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Yet another rebase of the same PR, after repository split. No tests obviously, just validated it manually publishing this version on my laptop.
=> Use updated rpc users config settings [CORDA-877]

constants.properties
Release 4.0.7 and update master to 4.0.8-SNAPSHOT
=> Begin 4.0.8-SNAPSHOT

cordformation/src/main/kotlin/net/corda/plugins/Node.kt
=> Fixes for webserver configuration [CORDA-1231]

changelog.md, constants.properties
The change log update was added to the 4.0.15 release.
=> Begin 4.0.16-SNAPSHOT

constants.properties
To match Corda upgrading to Kotlin 1.2.41.
=> CORDA-1441: Upgrade to Kotlin 1.2.41

changelog.md, cordapp/build.gradle, cordapp/src/main/kotlin/net/corda/plugins/CordappInfoExtension.kt, cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt, cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt, cordapp/src/test/resources/net/corda/plugins/CorDappWithInfo.gradle
https://r3-cev.atlassian.net/browse/CORDA-1469
=> [CORDA-1469]: Add manifest attributes for CorDapps from CorDapp plugin.

changelog.md, constants.properties, cordformation/src/main/kotlin/net/corda/plugins/Node.kt
As part of https://r3-cev.atlassian.net/browse/CORDA-1461, devMode is set to false by default.
Cordformation will set it to true.
=> CORDA-1461 set devMode=true and add config option

constants.properties, cordform-common/src/main/java/net/corda/cordform/CordformNode.java, cordformation/src/main/kotlin/net/corda/plugins/Node.kt
CORDA-1461 move devMode to CorformNode to be accessible programatically
=> CORDA-1461 move devMode to CorformNode to be accessible programatically

changelog.md, constants.properties
Not sure what happened in 4.0.19...
=> Begin 4.0.20-SNAPSHOT

changelog.md, constants.properties
4.0.24 released: https://ci-master.corda.r3cev.com/viewType.html?buildTypeId=CordaGradlePlugins_PublishToArtifactory&branch_CordaGradlePlugins=release%2F4.0.24&tab=buildTypeStatusDiv
=> Begin 4.0.25-SNAPSHOT

changelog.md, constants.properties
Upgraded version to 4.0.26-SNAPSHOT.
=> Version upgrades: 4.0.26

changelog.md, cordformation/src/main/kotlin/net/corda/plugins/Node.kt
https://r3-cev.atlassian.net/browse/CORDA-1714
=> [CORDA-1714] Fix sshdPort config in Node.kt to match the config API.

changelog.md, cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt, cordformation/src/main/kotlin/net/corda/plugins/Node.kt, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
Update all hard-coded references to jolokia 1.3.7, to the latest version (1.6.0)
=> CORDA-1737 update jolokia to latest version

cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻
Thanks for your code, it's appreciated! :)
=> Updated to provide Tmux support on Linux

jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterTimestampTest.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixTimestampTest.kt
Fix issues noticed in passing.
=> Trivial tweaks to test: fix warnings, rename variable.

build.gradle
Update ASM for bug-fixes to`COMPUTE_MAXS`. Full changelog for ASM 6.2.1. is [here](https://asm.ow2.io/versions.html#6.2.1).
=> CORDA-1876: Upgrade JarFilter to use ASM 6.2.1.

build.gradle
[ChangeLog for Kotlin 1.2.61](https://github.com/JetBrains/kotlin/releases/tag/v1.2.61).
=> CORDA-1910: Upgrade to Kotlin 1.2.61.

cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
This PR is to make the node runner maintainable again. It should never have been more than a branching set of if statements.
=> Returning node runner to a basic script to remove unnecessary complexity

build.gradle, changelog.md, cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt, cordapp/src/main/kotlin/net/corda/plugins/Info.kt, cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt, cordapp/src/test/resources/net/corda/plugins/CorDappWithInfo.gradle
https://r3-cev.atlassian.net/browse/CORDA-2025
=> [CORDA-2025] target and min platform version (cordapp plugin)

changelog.md, cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt, cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt
Cordapp plugin - Signed CorDapp JAR is also marked as sealed.
https://r3-cev.atlassian.net/browse/CORDA-2096
=> CORDA-2096 Mark JARs as sealed during signing

changelog.md
Move SignJar changelog entry to the correct release version.
=> Fix SignJar changelog entry.

build.gradle
Read Artifactory credentials from the environment first, and failing that from the system properties.
=> Fix credentials for publishing to Artifactory.

README.md, build.gradle, changelog.md
=> Bumped to snapshot 4.0.36

changelog.md
Added entry in `changelog.md`.
=> Added change log entry for signing key fix.

api-scanner/README.md, build.gradle, changelog.md
Bumping the version after release of 4.0.39
=> Bump version after release

build.gradle, changelog.md
=> Bump master version fo 4.0.41-SNAPSHOT

changelog.md, cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
* Unregister all SecurityProvider instances installed by Network Bootstrapper.
* Review fixes.
=> CORDA-2676: Unregister all SecurityProvider instances installed by Network Bootstrapper.

jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterAnnotations.kt, jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt, jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt, jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterConfigurationTest.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterProject.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterTimestampTest.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConfigurationTests.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorDefaultParameterTest.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFunctionDefaultParameterTest.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixProject.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixTimestampTest.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseDeleteConstructorTest.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseStubConstructorTest.kt, jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/UtilsTest.kt
* Update JarFilter to use Gradle Property and Provider classes.
* Use kotlin.test.fail instead of throwing AssertionError.
=> CORDA-2897: Update JarFilter to use Gradle Property and Provider classes.

changelog.md, cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt, quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy, quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
* Automatically apply `java` plugin when applying `quasar-utils`.
* Trivial tweaks to Cordformation logging.
=> CORDA-2713: Update quasar-utils to apply java plugin automatically. (#178)

changelog.md, quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy, quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy
This is the pull-request for the [Issue-216](https://github.com/corda/corda-gradle-plugins/issues/216)
As described in the issue, the missing exclusions were added to the jvmArgs.
I agree to the agreement in CONTRIBUTING.md.
=> Added exclusions in jvmArgs.

CONTRIBUTORS.md, changelog.md, quasar-utils/src/main/groovy/net/corda/plugins/QuasarExtension.groovy, quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy, quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy, quasar-utils/src/test/groovy/net/corda/plugins/Utilities.groovy, quasar-utils/src/test/resources/src/test/java/BasicTest.java
=> Replace `quasar_exclusions` project property with a `quasar` extension. (#218)

changelog.md, quasar-utils/src/main/groovy/net/corda/plugins/QuasarExtension.groovy, quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy, quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy, quasar-utils/src/test/resources/repositories.gradle
Expose the Quasar agent's `verbose` and `debug` options using the new `quasar` extension.
=> CORDA-2948: Add Quasar options for debug and verbose.

changelog.md, quasar-utils/src/main/groovy/net/corda/plugins/QuasarExtension.groovy, quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy, quasar-utils/src/test/groovy/net/corda/plugins/QuasarPluginTest.groovy, quasar-utils/src/test/resources/repositories.gradle
Expose the Quasar agent's verbose and debug options using the new quasar extension.
=> CORDA-2948: Add Quasar options for debug and verbose. (#221)

build.gradle, changelog.md
Feature parity with the 5.x releases.
=> Begin 4.0.46-SNAPSHOT.

changelog.md, cordformation/src/main/kotlin/net/corda/plugins/Node.kt, cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
see https://r3-cev.atlassian.net/browse/CORDA-3024
This change is needed to enable the renaming in the main repo
=> CORDA-3024 Rename corda-webserver

cordformation/src/main/kotlin/net/corda/plugins/Node.kt, cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
Minor stylistic points and whitespace.
=> Small tweaks to Cordformation.

CONTRIBUTORS.md, changelog.md, cordformation/src/main/kotlin/net/corda/plugins/Node.kt, cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt, cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle
Forward port Cordformation contribution from Ben Shi into 5.x branch.
=> Add support for OU when generating nodes directories.

CONTRIBUTORS.md, changelog.md, cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
Avoid exceptions when `--base-debug-port` or `--base-monitoring-port` not specified.
Remove a small amount of duplication.
Add William Yang to list of contributors.
=> Minor refactor to NodeRunner to prepare for release.

api-scanner/src/main/java/net/corda/plugins/ApiScanner.java, api-scanner/src/main/java/net/corda/plugins/GenerateApi.java, api-scanner/src/main/java/net/corda/plugins/ScanApi.java, cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt, cordformation/src/main/kotlin/net/corda/plugins/Cordform.kt, cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt, jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt, jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt, jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt
Fix issue #245  - Cordformation, API Scanner and Jar Filter.
=> Set groups and descriptions for our Gradle tasks.

changelog.md
Make the markdown consistent again.
=> NOTICK: Fix changelog formatting.

CONTRIBUTORS.md, api-scanner/build.gradle, api-scanner/src/main/java/net/corda/plugins/ScanApi.java, build.gradle, changelog.md, cordapp/build.gradle, cordapp/src/test/kotlin/net/corda/plugins/CordappGradleConfigurationsTest.kt, cordapp/src/test/kotlin/net/corda/plugins/CordappLibraryGradleConfigurationsTest.kt, cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle, jar-filter/build.gradle, jar-filter/src/test/resources/repositories.gradle, jar-filter/unwanteds/build.gradle, publish-utils/src/main/groovy/net/corda/plugins/MavenMapper.groovy
- Make 5005 & 7005 port configurable to avoid port conflict if running two.
- CORDA-3453: Fix NPE in publish-utils when publishing dependencies from a custom Gradle configuration.
=> NOTICK: Backport changes from master 5.x branch.

api-scanner/build.gradle, api-scanner/src/main/java/net/corda/plugins/GenerateApi.java, api-scanner/src/main/java/net/corda/plugins/ScanApi.java, build.gradle, cordapp/build.gradle, cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt, cordformation/build.gradle, cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt, jar-filter/build.gradle, jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt, jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt, jar-filter/unwanteds/build.gradle, publish-utils/build.gradle
Tidy up usage of Gradle. Also ask Gradle to sanity-check how we have annotated all of our `Task` properties.
=> NOTICK: Tidy up our usage of Gradle API.

README.md
Provide a brief description of what each Gradle plugin actually _does_, in case anyone was wondering...
=> NOTICK: Update the top-level README with a summary of each plugin.

build.gradle
Apply the `idea`  Gradle plugin to help integrate better with IntelliJ.
=> NOTICK: Add idea plugin to all sub-projects.

CONTRIBUTORS.md, changelog.md, cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt, cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt, cordformation/src/main/kotlin/net/corda/plugins/Node.kt, cordformation/src/main/kotlin/net/corda/plugins/TypesafeUtils.kt, cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt, cordformation/src/test/kotlin/net/corda/plugins/DockerformTest.kt, cordformation/src/test/kotlin/net/corda/plugins/TypesafeUtilsTest.kt, cordformation/src/test/resources/gradle.properties, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithNetworkConfigWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExternalDBSettingsWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle, cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithNetworkConfigWithDocker.gradle, cordformation/src/test/resources/postgres.gradle, cordformation/src/test/resources/repositories.gradle
PR to merge feature EG-117 Dockerform default to postgres into master
=> Feature/EG-117 Allow Postgres DB to be used with Dockerform

cordformation/src/main/kotlin/net/corda/plugins/DockerImage.kt
Resolve warnings from Kotlin compiler and from Gradle's task property validation.
=> NOTICK: Resolve some compiler warnings.

build.gradle
Upgrade the following plugins:
- Gradle Publish
- Artifactory
- Bintray
Also upgrade ClassGraph and JUnit Jupiter libraries.
=> NOTICK: Upgrade project plugins.

build.gradle, cordformation/build.gradle, jar-filter/build.gradle
Good Gradle hygiene means that we create as few tasks as possible when configuring the project.
=> NOTICK: Use task configuration avoidance in build.gradle scripts.

quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
This is not a user-visible change, unless you perform a build scan on your Gradle project. The `configureEach {}` API was introduced in Gradle 4.9.
=> CORDA-3884: Use Gradle's task configuration avoidance APIs for quasar-utils.

.github/CODEOWNERS
Add initial code owners for Gradle plugins
=> INFRA-446 Add CODEOWNERS file

cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
Register the `configureCordappFatJar` task for lazy configuration as well.
=> CORDA-3884: Use Gradle's task configuration avoidance APIs for cordapp.

cordformation/src/main/kotlin/net/corda/plugins/DockerImage.kt, cordformation/src/main/kotlin/net/corda/plugins/Node.kt, cordformation/src/test/kotlin/net/corda/plugins/DockerformTest.kt
Compiler warnings, and Gradle validation warnings on task inputs.
=> NOTICK: Resolve some build warnings.

.ci/Jenkinsfile
Added collection of JUnit tests.
Also switches build to more suitable Jenkins agent and keeps history for longer
=> NOTICK: Added missing collection of JUnit tests

changelog.md, quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy, quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy
Replace obsolete 0.7.10-jdk8 with 0.7.13_r3.
=> CORDA-3934: Upgrade default Quasar version to 0.7.13_r3.

quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy
Apply `quasar-utils` plugin more realistically in test scripts, and do not force Gradle to resolve test configurations.
=> NOTICK: Update unit test for quasar-utils plugin. (No functional change.)

api-scanner/src/main/java/net/corda/plugins/apiscanner/GenerateApi.java, api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java
Forward ported from the `release/5.0` branch.
=> NOTICK: Resolve Gradle deprecation warnings in API Scanner.

changelog.md, cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt, cordformation/src/main/kotlin/net/corda/plugins/CordaMock.kt, cordformation/src/main/kotlin/net/corda/plugins/Cordapp.kt, cordformation/src/main/kotlin/net/corda/plugins/Cordform.kt, cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt, cordformation/src/main/kotlin/net/corda/plugins/DockerImage.kt, cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt, cordformation/src/main/kotlin/net/corda/plugins/Node.kt, cordformation/src/main/kotlin/net/corda/plugins/RpcSettings.kt, cordformation/src/test/kotlin/net/corda/plugins/Assertions.kt, cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt, cordformation/src/test/kotlin/net/corda/plugins/CordaMockTest.kt, cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt, cordformation/src/test/kotlin/net/corda/plugins/DockerformTest.kt, cordformation/src/test/kotlin/net/corda/plugins/KotlinCordformTest.kt, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithNetworkConfigWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExternalDBSettingsWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle, cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithNetworkConfigWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordapp.gradle.kts, cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithDocker.gradle, cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithExternalService.gradle, cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithExternalServiceNoOption.gradle
* Replace cordformation DSL Closure elements with Action.
* Remove unused imports.
Forward ported from #405.
=> CORE-1134: Replace cordformation DSL Closure elements with Action. (#405)

cordapp/build.gradle, cordformation/build.gradle, publish-utils/build.gradle
Fix deprecation warnings raised by Gradle 7, although we're not upgrading to Gradle 7 yet.
=> NOTICK: Fix Gradle deprecations (to be removed in Gradle 8).

cordapp-cpk/build.gradle, cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/OsgiExtension.kt, cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/SimpleKotlinCordappTest.kt, cordapp-cpk/src/test/resources/configure-corda-metadata/cordapp/src/main/kotlin/com/example/metadata/custom/ExampleContract.kt, cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/core/identity/package-info.java, cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/flows/package-info.java, cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/identity/package-info.java, cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/node/services/package-info.java, cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/node/services/persistence/package-info.java, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/core/node/services/CordaService.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/flows/Flow.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/flows/FlowException.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/flows/flowservices/dependencies/CordaInjectable.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/identity/AbstractParty.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/node/services/CordaService.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/node/services/ServiceLifecycleEvent.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/node/services/persistence/MappedSchema.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/ledger/contracts/ContractState.kt, cordapp-cpk/src/test/resources/gradle.properties, cordapp-cpk/src/test/resources/simple-kotlin-cordapp/src/main/kotlin/com/example/contract/states/ExampleState.kt, cordapp-cpk/src/test/resources/with-corda-metadata/contracts/src/main/kotlin/com/example/metadata/contracts/ExampleContract.kt, cordapp-cpk/src/test/resources/with-corda-metadata/contracts/src/main/kotlin/com/example/metadata/schemas/ExampleSchema.kt, cordapp-cpk/src/test/resources/with-corda-metadata/services/src/main/kotlin/com/example/metadata/services/ExampleService.kt, cordapp-cpk/src/test/resources/with-corda-metadata/workflows/src/main/kotlin/com/example/metadata/workflows/ExampleFlow.kt
Update the stub Corda API project used by the cordapp-cpk test cases to reflect API changes in Corda 5.
Also remove residual reference to Quasar.
=> CORE-268: Update Corda API used by test cases.

flask/build.gradle
Add publication info required by Gradle's publish-plugin.
=> NOTICK: Add Gradle publication info to flask plugin.

cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/flows/flowservices/dependencies/package-info.java, cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
Test cordformation against Corda with the latest API packages.
=> CORE-268: Update tests for compatibility with latest Corda 5.

api-scanner/src/main/java/net/corda/plugins/apiscanner/ApiPrintWriter.java, api-scanner/src/main/java/net/corda/plugins/apiscanner/GenerateApi.java, api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java, api-scanner/src/main/java/net/corda/plugins/apiscanner/ScannerExtension.java, cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt, cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt, cordformation/src/main/kotlin/net/corda/plugins/CordformationUtils.kt, cordformation/src/main/kotlin/net/corda/plugins/DockerImage.kt, cordformation/src/test/kotlin/net/corda/plugins/DockerImageTest.kt
- Make some wildcard imports explicit.
- Make internal CorDapp configurations invisible to other modules.
- Remove some `Project` references from `DockerImage` task.
=> NOTICK: Tidy up some technical debt.

cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/PackagingTask.kt
Simplify the CPK packaging task's `CopySpec`.
=> CORE-268: Simplify CPK packaging task.

cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/OsgiExtension.kt, cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/node/services/persistence/package-info.java, cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/services/package-info.java, cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/services/persistence/package-info.java, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/services/CordaService.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/services/ServiceLifecycleEvent.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/services/persistence/MappedSchema.kt, cordapp-cpk/src/test/resources/with-corda-metadata/contracts/src/main/kotlin/com/example/metadata/schemas/ExampleSchema.kt, cordapp-cpk/src/test/resources/with-corda-metadata/services/src/main/kotlin/com/example/metadata/services/ExampleService.kt
Realign the dummy Corda API with Corda 5, i.e.
`net.corda.v5.application.node.services.*` -> `net.corda.v5.application.services.*`.
=> CORE-268: Update Corda API used for testing.

changelog.md, cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt, cordformation/src/main/kotlin/net/corda/plugins/Node.kt, cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
Upgrade the default version of cordformation's Jolokia agent from 1.6.0 to 1.6.2.
=> CORE-1610: Upgrade default Jolokia version to 1.6.2.

cordapp-cpk/src/test/resources/corda-api/src/main/java/net/corda/v5/application/flows/flowservices/dependencies/package-info.java, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/flows/flowservices/dependencies/CordaInjectable.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/services/CordaService.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/services/ServiceLifecycleEvent.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/application/services/lifecycle/ServiceLifecycleEvent.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/ledger/contracts/Contract.kt, cordapp-cpk/src/test/resources/corda-api/src/main/kotlin/net/corda/v5/serialization/SingletonSerializeAsToken.kt
Realign the dummy Corda API with the latest Corda 5 API.
=> NOTICK: Realign dummy Corda API for testing CPKs.

cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CPKDependenciesTask.kt, cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappUtils.kt, cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/TransitiveCordappsTest.kt, cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/xml/XmlSchema.kt, cordapp-cpk/src/test/resources/transitive-cordapps/cpk-one/build.gradle, cordapp-cpk/src/test/resources/transitive-cordapps/cpk-two/build.gradle, cordapp-cpk/src/test/resources/xml/corda-cpk-1.0.xsd
=> [CORE-1744] Mark CPKs that belong to the Corda platform in the CPKDependencies file

quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
Upgrade the default Quasar agent from 0.8.6_r3 to 0.8.7_r3.
=> CORE-1790: Update default Quasar version to 0.8.7_r3.

flask/README.md, flask/flask-common/src/main/java/net/corda/flask/common/Flask.java, flask/flask-launcher/src/main/java/net/corda/flask/launcher/Launcher.java, flask/src/test/groovy/net/corda/gradle/flask/FlaskPluginTest.groovy, flask/src/test/resources/testProject/build.gradle, flask/src/test/resources/testProject/src/main/java/net/corda/gradle/flask/test/AlternativeMain.java, flask/src/test/resources/testProject/src/main/java/net/corda/gradle/flask/test/Main.java
added a Java system property to allow for launching a Flask jar without its embedded Java agents
=> [CORE-1863] Allow for running without Java agents

flask/README.md
=> Fixed typos in README.md

build.gradle, cordapp-cpk/src/test/kotlin/net/corda/plugins/cpb/CpbTest.kt, cordapp-cpk/src/test/kotlin/net/corda/plugins/cpk/WithoutTransitiveCordappsTest.kt, cordapp-cpk/src/test/resources/cordapp-cpb/build.gradle, cordapp-cpk/src/test/resources/cordapp-cpb/project-dependency/build.gradle, cordapp-cpk/src/test/resources/external-cordapp/build.gradle, cordapp-cpk/src/test/resources/external-cordapp/corda-platform-cordapp/build.gradle, cordapp-cpk/src/test/resources/transitive-cordapps/build.gradle, cordapp-cpk/src/test/resources/transitive-cordapps/cpk-one/build.gradle, cordapp-cpk/src/test/resources/transitive-cordapps/cpk-three/build.gradle, cordapp-cpk/src/test/resources/transitive-cordapps/cpk-two/build.gradle, cordapp-cpk/src/test/resources/without-transitive-cordapps/build.gradle, cordapp-cpk/src/test/resources/without-transitive-cordapps/cpk-one/build.gradle, cordapp-cpk/src/test/resources/without-transitive-cordapps/cpk-two/build.gradle
Update Gradle files for "best practices":
- Denote new configurations either for consuming or resolving.
- Prefer task configuration avoidance, where possible.
Also align `WithoutTransitiveCordappsTest` with `TransitiveCordappsTest`, use existing digest calculation functions, and remove more unnecessary `minimumPlatformVersion` properties.
=> NOTICK: Clean up some more Gradle technical debt.

build.gradle, cordapp-cpk/build.gradle, cordformation/build.gradle
Generate `SigningOptions` source in the correct package directory.
Also add licensing and developers to all POMs, including plugin markers.
=> NOTICK: Add SigningOptions to correct directory in sources jar.

.ci/Jenkinsfile, gradle.properties
Corrected branch name and applied fix, and some pipeline whitespace formatting
=> CORE-2568: Rollback plugin version

whitelist.txt
Declare the artifacts for publishing to Maven Staging.
=> CORE-2579: Add whitelist.txt for Maven Staging artifacts.

cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt, cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/DependencyCalculator.kt
Refactor CPK task dependency logic into the `Plugin.apply()` method.
=> NOTICK: Derive CPK task dependencies during Plugin.apply().

cordapp-cpk/src/main/kotlin/net/corda/plugins/cpb/CpbPlugin.kt, cordapp-cpk/src/main/kotlin/net/corda/plugins/cpk/CordappPlugin.kt
Align CPK and CPB versions with the "main" jar's version, by default.
=> NOTICK: Apply main jar version to CPK and CPB by default.

gradle.properties
Upgrade Bnd 6.1.0 -> 6.2.0.
Also upgrade the Gradle publish plugin 0.16.0 -> 0.20.0.
=> CORE-4083: Upgrade to Bnd 6.2.0.

api-scanner/build.gradle, build.gradle, cordapp-cpk/build.gradle, cordapp/build.gradle, cordformation/build.gradle, flask/build.gradle, gradle.properties, jar-filter/build.gradle, publish-utils/build.gradle, quasar-utils/build.gradle
[Release notes for Bnd 6.3.0](https://github.com/bndtools/bnd/wiki/Changes-in-6.3.0).
Also update Gradle's own `plugin-publish` plugin, for publishing these plugins to Gradle's Plugin Portal.
=> CORE-5052: Upgrade Bnd 6.2.0 -> 6.3.0.

gradle.properties
Upgrade Bnd 6.3.0 -> 6.3.1 to avoid [Bnd#5275](https://github.com/bndtools/bnd/issues/5275).
=> CORE-5146: Upgrade cordapp-cpk to use Bnd 6.3.1.

.ci/nightly/JenkinsfileSnykScan
Add nightly job to run Snyk CLI scan for vulnerability detection
Tested [here](https://ci02.dev.r3.com/job/Corda5/job/Snyk-Scans/job/corda-gradle-plugins-snyk-scan/job/CORE-5057%252Fadd-snyk/)
=> CORE-5057 add Jenkins job for Snyk CLI scan

cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CordappPlugin.kt, cordapp-cpk2/src/main/kotlin/net/corda/plugins/cpk2/CordappUtils.kt
=> CORE-4355: CPK Format version 2

.ci/Jenkinsfile
- calls snyk cli tool under the hood to run a test and generate reports 
- Exclude PR builds as they will be handled by separate logic at a later stage
- Generate HTML report on Build pipeline also if this has ran
=> CORE- 5660: add snyk scanning to the main CI build 

.ci/Jenkinsfile
Cherry pick of https://github.com/corda/corda-gradle-plugins/commit/18d04004d6d6405a790835d6f6ebd3b01e5c20e9
=> CORE- 5660: add snyk scanning to the main CI build 5.0 stream  (#515)

.ci/Jenkinsfile
Cherry pick of https://github.com/corda/corda-gradle-plugins/commit/18d04004d6d6405a790835d6f6ebd3b01e5c20e9
=> CORE- 5660: add snyk scanning to the main CI build - 6.0 (#515)

.ci/Jenkinsfile, .ci/nightly/JenkinsfileSnykScan
Removing .ci/nightly/JenkinsfileSnykScan as this is not needed. The existing CI needed to be amended so the following CI job just needs to run the additional Snyk stage for the release/5.1 branch:
https://ci01.dev.r3.com/job/Corda-Gradle-Build-Plugins/job/corda-gradle-plugins/job/release%252F5.1/ 
Similar change to https://github.com/corda/corda-gradle-plugins/pull/515
=> CORE-5071: Add snyk Gradle plugin to C5 projects

gradle.properties
This fixes vulnerabilities reported by Snyk in `cordformation`.
=> CORE-5730: Upgrade Docker client 8.15.1 -> 8.16.0

.ci/Jenkinsfile, cordformation/build.gradle, gradle.properties
Upgrade the following dependencies for `docker-client`:
- Jackson
- BouncyCastle
- Snake YAML
- `commons-codec`
- `commons-collection`
- `commons-io`
- `httpclient`
=> CORE-5730: Upgrade dependencies for docker-client.

.ci/Jenkinsfile, cordformation/build.gradle, gradle.properties
Upgrade the following dependencies for `docker-client`:
- Jackson
- BouncyCastle
- Snake YAML
- `commons-codec`
- `commons-collection`
- `commons-io`
- `httpclient`
=> CORE-5730: Upgrade dependencies for docker-client

README.md, changelog.md, quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarExtension.groovy, quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy, quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy, quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarSuspendableTest.groovy
Back-ported from 7.0.0-SNAPSHOT.
=> CORE-6321: Revert quasar-utils to using original Quasar agent.

build.gradle
Allow Jenkins to choose which Artifactory repository to publish to, and remove nonsense Java system properties.
=> NOTICK: Configure artifactory repository key for publication.

cordapp-cpk2/README.md
Update the readme file with some changes made for format version 2.
=> NOTICK: Update README.md for format version 2

gradle.properties
Increment snapshot version post cutting of 7.0.1 release tag
=> NOTICK: begin 7.0.2-SNAPSHOT post 7.0.1 being cut

CONTRIBUTORS.md, changelog.md, gradle.properties
Upgrade Bnd 6.3.1 -> 6.4.0. 
Also make the following minor upgrades:
- ASM 9.3 -> 9.4
- Jackson 2.13.4 -> 2.14.1
=> CORE-9328: Upgrade Bnd 6.3.1 -> 6.4.0.

.ci/Jenkinsfile
Disable auto PR comments from Jenkins on this repo as not required
=> NOTICK: no need to use gitHubComments on this repo

changelog.md, gradle.properties
Start the next development cycle.
=> NOTICK: Begin 7.0.3-SNAPSHOT.

cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt, gradle.properties
Upgrade HttpClient 4.15.13 -> 4.5.14.
Also upgrade Log4J2, for testing purposes.
=> CORE-13907: Upgrade httpclient 4.5.13 -> 4.5.14.

api-scanner/build.gradle, cordapp-cpk2/build.gradle, cordapp-cpk2/src/main/java/net/corda/plugins/cpk2/PublishAfterEvaluationHandler.java, gradle.properties, jar-filter/build.gradle, quasar-utils/build.gradle
- Upgrade Artifactory plugin 4.29.2 -> 5.1.6.
- Upgrade JUnit 5.9.3 -> 5.10.0.
Ensure `net.corda.plugins.cordapp-cpk2` is compatible with Artifactory plugin 5.x.
=> CORE-17034: Upgrade to support Artifactory plugin 5.x.
